### PR TITLE
Added DscResourcesToExport to module manifest - Fixes #86

### LINKED ISSUE #86: Add DscResourcesToExport to Manifest
To improve the information in the PowerShellGallery, add DscResourcesToExport to the module manifest.

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR adds the DscResourcesToExport to the module manifest to improve information in PowerShell Gallery.

#### This Pull Request (PR) fixes the following issues

- Fixes #86

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju - no rush on this one. Would you mind reviewing when you have a moment? Should be trivial.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/87)

### CODE REVIEW

**Review by johlju — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/87)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

*[a discussion](https://reviewable.io/reviews/powershell/dfsdsc/87#-LXDvbwK5aLqB6KHdh6D:-LXDvbwK5aLqB6KHdh6E:b76bodx) (no related file):*
Tests are failing on this one.

---

**Comment by PlagueHO** [comment]
Should be good to go now @johlju. I added some more detail into the CHANGELOG.MD as well to document the manifest changes. Thanks again!

**Review by johlju — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/87#-:-LXKksNt3MndlIhSLBiw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by PlagueHO** [comment]
Thanks @johlju

**Pull request merged**
