### PR TITLE
DFSReplicationGroup - update PrimaryMember to write-only but not test

### LINKED ISSUE #58: xDFSReplicationGroup - test-targetresource always returns PrimaryMember as true
**Details of the scenario you tried and the problem that is occurring:**
I am trying to configure an existing DFS Replication group using xDFS. I have the PrimaryMember flag set to $false in the DSC configuration and I can confirm when running Get-DFSRMembership, primarymember is set to false as well. But when I run Start-DscConfiguration, Test-TargetResource returns $false because:
Test-TargetResource: DFS Replication Group "****" folder "****" on "****" has incorrect PrimaryMember. Change required.

Verbose Output when running start-dscconfiguration
VERBOSE: [hostname]: LCM:  [ Start  Test     ]  [[xDFSReplicationGroupMembership]Admin-Membership]
VERBOSE: [hostname]:                            [[xDFSReplicationGroupMembership]Admin-Membership] Test-TargetResource: Testing DFS Replication Group "replicationgroup" folder "replicatedfolder" on "hostname".
VERBOSE: [hostname]:                            [[xDFSReplicationGroupMembership]Admin-Membership] Test-TargetResource: DFS Replication Group "replicationgroup" folder "replicatedfolder" on "hostname" exists.
VERBOSE: [hostname]:                            [[xDFSReplicationGroupMembership]Admin-Membership] Test-TargetResource: DFS Replication Group "replicationgroup" folder "replicatedfolder" on "hostname" has incorrect PrimaryMember. Change required.
VERBOSE: [hostname]: LCM:  [ End    Test     ]  [[xDFSReplicationGroupMembership]Admin-Membership]  in 0.2500 seconds.

Verbose Output when Manually running test-targetresource
Test-TargetResource -GroupName "replicationgroup" -FolderName "replicatedfolder" -ComputerName "hostname"
VERBOSE: Test-TargetResource: Testing DFS Replication Group "replicationgroup" folder "replicatedfolder" on "hostname".
VERBOSE: Test-TargetResource: DFS Replication Group "replicationgroup" folder "folder" on "hostname" exists.
True

**The DSC configuration that is using the resource (as detailed as possible):**
            xDFSReplicationGroupMembership "$($DFSRConfig.ShareName)-Membership" {
                GroupName            = $DFSRConfig.ReplicationGroupName
                FolderName           = $DFSRConfig.ReplicatedFolder
                ComputerName         = $hostname
                ContentPath          = $DFSRConfig.ShareDestinationPath
                PrimaryMember        = $false
                StagingPath          = $DFSRConfig.StagingPath
                StagingPathQuotaInMB = $DFSRConfig.StagingPathQuotaInMB
                PSDSCRunAsCredential = $Credential
                DomainName           = $DFSRConfig.DomainName
                DependsOn            = @("[File]$($DFSRConfig.ShareName)-StagingPath", "[xDFSReplicationGroupFolder]$($DFSRConfig.ShareName)-ReplicatedFolder")
            }

**Version of the Operating System and PowerShell the DSC Target Node is running:**
OS: Windows Server 2016 Datacenter
PowerShell: 
Name                           Value
----                           -----
PSVersion                      5.1.14393.1944
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.1944
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
3.2.0.0

### PR DESCRIPTION
**Pull request by Borgquite**
#### Pull Request (PR) description

Make PrimaryMember a write-only property that should not test

#### This Pull Request (PR) fixes the following issues

- Fixes #58 

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/DFSDsc/138)

### CODE REVIEW

**Comment by Borgquite** [comment]
Hey @PlagueHO - sorry, me again. Hope this is a quick one, let me know if you have any comments/suggestions :) Ta!

**Comment by PlagueHO** [comment]
Hi @Borgquite - sorry about t the delay. Been at a vibe come conference all week so will try and get into this over the weekend!

**Comment by Borgquite** [comment]
No worries @PlagueHO - any free time you have much appreciated :)

**Review by PlagueHO — CHANGES_REQUESTED** [review]
Just minor style nit picks.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DFSDsc/138#-:-NvLIR-W9W7EPljb98G1:bcxbm7g)* status: all files reviewed, 4 unresolved discussions (waiting on @Borgquite)

___
*[`CHANGELOG.md` line 8 at r1](https://reviewable.io/reviews/dsccommunity/DFSDsc/138#-NvLHqNR200mmOY7QWw-:-NvLHqNR200mmOY7QWw0:b-10emr9) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/bd0e2f2d5db6865745180f8bf693f27808bac891/CHANGELOG.md#L8)):*
> ```Markdown
> ## [Unreleased]
> 
> ### Fixed
> ```

Can you add a blank line after this one?
___
*[`source/DSCResources/DSC_DFSReplicationGroupMembership/DSC_DFSReplicationGroupMembership.psm1` line 537 at r1](https://reviewable.io/reviews/dsccommunity/DFSDsc/138#-NvLI0TVDFmuO7uXdPDS:-NvLI0TVDFmuO7uXdPDT:b-m3dbt4) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/bd0e2f2d5db6865745180f8bf693f27808bac891/source/DSCResources/DSC_DFSReplicationGroupMembership/DSC_DFSReplicationGroupMembership.psm1#L537)):*
> ```PowerShell
>                 ) -join '' )
> 
>             # See https://techcommunity.microsoft.com/t5/storage-at-microsoft/the-primary-member-in-dfs-replication/ba-p/423127
> ```

Could you change to a <# #> comment block?
___
*[`source/DSCResources/DSC_DFSReplicationGroupMembership/DSC_DFSReplicationGroupMembership.schema.mof` line 16 at r1](https://reviewable.io/reviews/dsccommunity/DFSDsc/138#-NvLI7TR71rQMQNBIAdb:-NvLI7TR71rQMQNBIAdc:bh5qpu9) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/bd0e2f2d5db6865745180f8bf693f27808bac891/source/DSCResources/DSC_DFSReplicationGroupMembership/DSC_DFSReplicationGroupMembership.schema.mof#L16)):*
> ```
>     [Write, Description("Specify if this content path should be read only.")] Boolean ReadOnly;
>     [Write, Description("Specify if a member computer deletes files and folders immediately following inbound replication.")] Boolean RemoveDeletedFiles;
>     [Write, Description("Used to configure this as the Primary Member. Every folder must have at least one primary member for initial replication to take place.  Only set during initial creation of membership.")] Boolean PrimaryMember;
> ```

Can you change to single space before `Only`?
___
*[`source/DSCResources/DSC_DFSReplicationGroupMembership/README.md` line 7 at r1](https://reviewable.io/reviews/dsccommunity/DFSDsc/138#-NvLIGDb5aO_w1YanXan:-NvLIGDb5aO_w1YanXao:b-hbyjoj) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/bd0e2f2d5db6865745180f8bf693f27808bac891/source/DSCResources/DSC_DFSReplicationGroupMembership/README.md#L7)):*
Can you move NB to be on a new paragraph and use:

`
> Note: ...
`

**Review by Borgquite — COMMENTED** [review]
No worries - all done :)

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DFSDsc/138#-:-NvWFqPvC54kqIs_cuvq:b-jenwn4)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @PlagueHO)

___
*[`CHANGELOG.md` line 8 at r1](https://reviewable.io/reviews/dsccommunity/DFSDsc/138#-NvLHqNR200mmOY7QWw-:-NvWFveR-v8ftETfKIHg:b-896fix) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/bd0e2f2d5db6865745180f8bf693f27808bac891/CHANGELOG.md#L8)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a blank line after this one?
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_DFSReplicationGroupMembership/DSC_DFSReplicationGroupMembership.psm1` line 537 at r1](https://reviewable.io/reviews/dsccommunity/DFSDsc/138#-NvLI0TVDFmuO7uXdPDS:-NvWFwKn6HW7wHj6W4F0:b-896fix) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/bd0e2f2d5db6865745180f8bf693f27808bac891/source/DSCResources/DSC_DFSReplicationGroupMembership/DSC_DFSReplicationGroupMembership.psm1#L537)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could you change to a <# #> comment block?
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_DFSReplicationGroupMembership/DSC_DFSReplicationGroupMembership.schema.mof` line 16 at r1](https://reviewable.io/reviews/dsccommunity/DFSDsc/138#-NvLI7TR71rQMQNBIAdb:-NvWFx7HBwvrn0fV-L_C:b-896fix) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/bd0e2f2d5db6865745180f8bf693f27808bac891/source/DSCResources/DSC_DFSReplicationGroupMembership/DSC_DFSReplicationGroupMembership.schema.mof#L16)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you change to single space before `Only`?
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_DFSReplicationGroupMembership/README.md` line 7 at r1](https://reviewable.io/reviews/dsccommunity/DFSDsc/138#-NvLIGDb5aO_w1YanXan:-NvWFxrfAuFpIz6bGswo:b-896fix) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/bd0e2f2d5db6865745180f8bf693f27808bac891/source/DSCResources/DSC_DFSReplicationGroupMembership/README.md#L7)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you move NB to be on a new paragraph and use:

`
> Note: ...
`
</blockquote></details>

Done.

**Review by PlagueHO — CHANGES_REQUESTED** [review]
Sorry minor clarifications :D

> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DFSDsc/138#-:-Nv_V62m3zEqQo7DYflO:bf78hk8)* status: all files reviewed, 2 unresolved discussions (waiting on @Borgquite)

___
*[`source/DSCResources/DSC_DFSReplicationGroupMembership/DSC_DFSReplicationGroupMembership.psm1` line 537 at r1](https://reviewable.io/reviews/dsccommunity/DFSDsc/138#-NvLI0TVDFmuO7uXdPDS:-Nv_UeYC1Ey2tUDQG3WP:b-f8zxmj) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/bd0e2f2d5db6865745180f8bf693f27808bac891/source/DSCResources/DSC_DFSReplicationGroupMembership/DSC_DFSReplicationGroupMembership.psm1#L537)):*
<details><summary><i>Previously, Borgquite (Chris Hill) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Apologies, I meant like this:
<#
    See https://techcommunity.microsoft.com/t5/storage-at-microsoft/the-primary-member-in-dfs-replication/ba-p/423127
    Do not flag as a change required as flag is cleared after initial sync
#>
___
*[`source/DSCResources/DSC_DFSReplicationGroupMembership/README.md` line 7 at r1](https://reviewable.io/reviews/dsccommunity/DFSDsc/138#-NvLIGDb5aO_w1YanXan:-Nv_Uo2PEhoJtZbsLH3e:bvj5ac0) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/bd0e2f2d5db6865745180f8bf693f27808bac891/source/DSCResources/DSC_DFSReplicationGroupMembership/README.md#L7)):*
Ah, I see Reviewable helpfully converted by example to MD.

Can you prepend:
```
> Note: The PrimaryMember flag is automatically cleared by DFS once an initial
> replication sync takes place, so is not tested by this resource.
```

This will make the MD format it.

**Review by Borgquite — COMMENTED** [review]
No worries - all OK now?

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DFSDsc/138#-:-Nvab1jH5QGA12IvToAB:b9a9h0g)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[`source/DSCResources/DSC_DFSReplicationGroupMembership/DSC_DFSReplicationGroupMembership.psm1` line 537 at r1](https://reviewable.io/reviews/dsccommunity/DFSDsc/138#-NvLI0TVDFmuO7uXdPDS:-Nvab0LJCAx62N4J42DB:b-896fix) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/bd0e2f2d5db6865745180f8bf693f27808bac891/source/DSCResources/DSC_DFSReplicationGroupMembership/DSC_DFSReplicationGroupMembership.psm1#L537)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Apologies, I meant like this:
<#
    See https://techcommunity.microsoft.com/t5/storage-at-microsoft/the-primary-member-in-dfs-replication/ba-p/423127
    Do not flag as a change required as flag is cleared after initial sync
#>
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_DFSReplicationGroupMembership/README.md` line 7 at r1](https://reviewable.io/reviews/dsccommunity/DFSDsc/138#-NvLIGDb5aO_w1YanXan:-Nvab1E5E6j1ydv3PbPu:b-896fix) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/bd0e2f2d5db6865745180f8bf693f27808bac891/source/DSCResources/DSC_DFSReplicationGroupMembership/README.md#L7)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Ah, I see Reviewable helpfully converted by example to MD.

Can you prepend:
```
> Note: The PrimaryMember flag is automatically cleared by DFS once an initial
> replication sync takes place, so is not tested by this resource.
```

This will make the MD format it.
</blockquote></details>

Done.

**Review by PlagueHO — APPROVED** [review]
:lgtm:

Thanks @Borgquite !

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DFSDsc/138#-:-Nvn-0KzB7VBYn-bNAnU:bxbfmyj)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Borgquite)

**Comment by Borgquite** [comment]
@microsoft-github-policy-service agree company="Mission Aviation Fellowship International"

**Pull request merged**
