### PR TITLE
Added Hub and Spoke Topology Examples - Fixes #62

### LINKED ISSUE #62: Add an example to show how to create a Hub and Spoke Topology
Trying to use DFSDsc not to ensure a configuration but to do setup work.  I have a scenario where Im using an Azure ARM template to call DFSDsc.  My member nodes array could be 2 servers or 10 and with not supporting the Hub and Spoke technology I have to find a way to run DFSGroupConnections multiple times if there are more than two nodes in my member nodes group.  The big picture is to be able to use this for 2 servers or 10 without having to hardcode values.  Hub and Spoke support would allow me to do that.  We do not want to implement full mesh due to network traffic

**The DSC configuration that is using the resource (as detailed as possible):**
xDFS

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows server 2012 and 2016

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
Latest version

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
This PR adds an example of how to create a hub and spoke DFS replication group topology.

**This Pull Request (PR) fixes the following issues:**
Fixes #62

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@johlju - I've tested this using a lab I built in LabBuilder: https://github.com/PlagueHO/LabBuilder/blob/dev/LabBuilder/dsclibrary/MEMBER_DFSHUB.DSC.ps1

Would you mind reviewing when you have time?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/64)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1, line 23 at r1](https://reviewable.io/reviews/powershell/dfsdsc/64#-LD60aCREUPpYaH35k0E:-LD60aCREUPpYaH35k0F:b5lpo1w) ([raw file](https://github.com/powershell/dfsdsc/blob/0d82b4b0a0b817a7f3c14984ac65532af9a58c92/Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1#L23)):*
> ```PowerShell
>         $Credential,
> 
>         [Parameter(Mandatory = $true)]
> ```

This the examples fail in test because this is mandatory instead of having a default value? Throughout the examples.

---

*[Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1, line 79 at r1](https://reviewable.io/reviews/powershell/dfsdsc/64#-LD5zJ-v6CowlITJhD6_:-LD5zJ-v6CowlITJhD6a:b-f7k3jj) ([raw file](https://github.com/powershell/dfsdsc/blob/0d82b4b0a0b817a7f3c14984ac65532af9a58c92/Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1#L79)):*
> ```PowerShell
> 
>         # Configure the connection and membership for each Spoke
>         foreach ($spoke in $SpokeComputerName) {
> ```

Open brace on separate row. Throughout the examples.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/64)*

**Comment by johlju** [comment]
Seeing this example (duplicated in each resource) it feels like the auto-document feature should support examples on resource module level too? 🤔

**Comment by johlju** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1, line 6 at r2](https://reviewable.io/reviews/powershell/dfsdsc/64#-LD65XL783au0VEd1FYz:-LD65XL783au0VEd1FZ-:bdb6y3c) ([raw file](https://github.com/powershell/dfsdsc/blob/0347b5cfd9ce6009199b41a183f85c047db685c1/Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1#L6)):*
> ```
> WebSiteFle
> ```

WebSiteFiles?

---

*[Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1, line 10 at r2](https://reviewable.io/reviews/powershell/dfsdsc/64#-LD65kC61u6F0jfaodnf:-LD65kC61u6F0jfaodng:b31vmms) ([raw file](https://github.com/powershell/dfsdsc/blob/0347b5cfd9ce6009199b41a183f85c047db685c1/Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1#L10)):*
> ```
> SopeComputerName
> ```

SpokeComputerName

---

*[Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1, line 11 at r2](https://reviewable.io/reviews/powershell/dfsdsc/64#-LD65h_JC-t46FX8rGVv:-LD65h_JC-t46FX8rGVw:bdnu5ar) ([raw file](https://github.com/powershell/dfsdsc/blob/0347b5cfd9ce6009199b41a183f85c047db685c1/Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1#L11)):*
> ```
> default
> ```

defaults ?

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/64)*

**Comment by PlagueHO** [comment]
Agreed - something that bothers me too. The problem we ran into was how to tell each wiki page which examples to include if they weren't in their own folder. We could have added meta data to each README.MD but that starts to get less "auto".

---

Review status: 1 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1, line 23 at r1](https://reviewable.io/reviews/powershell/dfsdsc/64#-LD60aCREUPpYaH35k0E:-LD65mzQ9QT_Cu1Or85u:b-5mxya7) ([raw file](https://github.com/powershell/dfsdsc/blob/0d82b4b0a0b817a7f3c14984ac65532af9a58c92/Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1#L23)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This the examples fail in test because this is mandatory instead of having a default value? Throughout the examples.
</blockquote></details>

Doh! Fixed.

---

*[Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1, line 79 at r1](https://reviewable.io/reviews/powershell/dfsdsc/64#-LD5zJ-v6CowlITJhD6_:-LD65p__CQZlsoD0_A3e:b-896fix) ([raw file](https://github.com/powershell/dfsdsc/blob/0d82b4b0a0b817a7f3c14984ac65532af9a58c92/Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1#L79)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Open brace on separate row. Throughout the examples.
</blockquote></details>

Done.

---

*[Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1, line 6 at r2](https://reviewable.io/reviews/powershell/dfsdsc/64#-LD65XL783au0VEd1FYz:-LD66mdm3njMoDvI2HEw:b-896fix) ([raw file](https://github.com/powershell/dfsdsc/blob/0347b5cfd9ce6009199b41a183f85c047db685c1/Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1#L6)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> WebSiteFle
> ```

WebSiteFiles?
</blockquote></details>

Done.

---

*[Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1, line 10 at r2](https://reviewable.io/reviews/powershell/dfsdsc/64#-LD65kC61u6F0jfaodnf:-LD66m6-11gIgem3FVkS:b-896fix) ([raw file](https://github.com/powershell/dfsdsc/blob/0347b5cfd9ce6009199b41a183f85c047db685c1/Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1#L10)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> SopeComputerName
> ```

SpokeComputerName
</blockquote></details>

Done.

---

*[Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1, line 11 at r2](https://reviewable.io/reviews/powershell/dfsdsc/64#-LD65h_JC-t46FX8rGVv:-LD66lok6SJLplxeDDmH:b-896fix) ([raw file](https://github.com/powershell/dfsdsc/blob/0347b5cfd9ce6009199b41a183f85c047db685c1/Modules/DFSDsc/Examples/Resources/DFSReplicationGroup/4_HubAndSpoke.ps1#L11)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> default
> ```

defaults ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/64#-:-LD65tEMBIgEVt4r-SAz:b-ufvq1c)*

**Comment by johlju** [comment]
:lgtm:

I seeing those examples being in the root of the Examples folder, and logic that checks each file (AST?) if that particular resource is present, then adds a link (maybe .SYSNOPSIS as descriptive text) from the resource Wiki page to the "example Wiki page". On Home-page there can be Example section with all the "general" examples that links to each "example Wiki page".

---

Reviewed 4 of 4 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/64#-:-LD6E0DK6JehfGNDi41-:b-b2dowf)*

**Comment by PlagueHO** [comment]
Great idea @johlju - that could definitely work! We should definitely make some improvements to the auto-documentation generation. Right now it doesn't actually generate the "home page" README.MD or the _SIDEBAR.MD. I've submitted these as issues to DSCResources.Tests so I can work on them.

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/64#-:-LD6Ez7P6wum1HmT3l-p:b-tu2poe)*

**Pull request merged**
