### PR TITLE
DFSNamespaceServerConfiguration: Add EnableSiteCostedReferrals, EnableInsiteReferrals, PreferLogonDC parameters

### PR DESCRIPTION
**Pull request by Borgquite**
#### Pull Request (PR) description

Add EnableSiteCostedReferrals, EnableInsiteReferrals, PreferLogonDC parameters to DFSNamespaceServerConfiguration so these settings can be set on the entire server.

See https://learn.microsoft.com/en-us/powershell/module/dfsn/get-dfsnserverconfiguration?view=windowsserver2022-ps

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/DFSDsc/134)

### CODE REVIEW

**Comment by Borgquite** [comment]
Came across a weird error in setting up integration tests these - in the test environment running these commands:

```
Set-DfsnServerConfiguration -ComputerName <servername> -EnableSiteCostedReferrals $true
Set-DfsnServerConfiguration -ComputerName <servername> -EnableInsiteReferrals $true
Set-DfsnServerConfiguration -ComputerName <servername> -PreferLogonDC $true
```

appear to throw this error in the underyling cmdlet (yes, there are spelling mistakes there):

```
Set-DfsnServerConfiguration : Cannot set parameter "Enable site costed refferals" on server "<servername>"
Set-DfsnServerConfiguration : Cannot read parameter "Enable insite referrals" on server "<servername>"
Set-DfsnServerConfiguration : Cannot set parameter "Prefer logon DC" on server "<servername>"
```

Could be related to how Get-DfsnServerConfiguration returns an empty string for this and other values when first configured? (#15)?

I think it might be that these commands are only supported on a domain-based DNS namespace server, whereas I am guessing our integration environment is a standalone server? The cmdlets seem to work fine in 'real life' so I've left them out of the integration tests and added a note to the relevant help. Hope this is acceptable :)

**Review by johlju — CHANGES_REQUESTED** [review]
Yes unfortunately we don't have any domain joined server to run such tests on. Having separate integration tests that can be run locally is an option, but a bit complex to maintain and verify so I think your suggestion is acceptable. :slightly_smiling_face: 

> Reviewed 3 of 7 files at r1, 2 of 2 files at r2, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DFSDsc/134#-:-Nqcvqkr9Kez3nwVdEpH:b536jsy)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @Borgquite)

___
*[`CHANGELOG.md` line 7 at r3](https://reviewable.io/reviews/dsccommunity/DFSDsc/134#-Nqcwe9y2OqPlsQjYGIb:-Nqcwe9y2OqPlsQjYGIc:braxgl) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/6de67cd9ce771e0efce05a1dd56a0eca3c4bb4d1/CHANGELOG.md#L7)):*
> ```Markdown
> 
> ## [Unreleased]
> ```

Add section `### Added` (see Keep a changelog link). I missed that in the PR I merged, when you rebase please ass the existing entry under `### Fixed` or `### Chnaged`.

**Review by Borgquite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DFSDsc/134)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[`CHANGELOG.md` line 7 at r3](https://reviewable.io/reviews/dsccommunity/DFSDsc/134#-Nqcwe9y2OqPlsQjYGIb:-Nqd2d9-6ZemJTjOqZj5:b-896fix) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/6de67cd9ce771e0efce05a1dd56a0eca3c4bb4d1/CHANGELOG.md#L7)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Add section `### Added` (see Keep a changelog link). I missed that in the PR I merged, when you rebase please ass the existing entry under `### Fixed` or `### Chnaged`.
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DFSDsc/134#-:-Nqd4jBGDf3tglPR3bXY:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Borgquite)

**Review by johlju — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DFSDsc/134)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Borgquite)

**Pull request merged**
