### PR TITLE
DFSNamespaceRoot, DFSNamespaceFolder - Support for setting the root / folder State

### PR DESCRIPTION
**Pull request by Borgquite**
#### Pull Request (PR) description

This PR allows the 'State' parameter on the DFSNamespaceRoot and DFSNamespaceFolder to be modified as part of a configuration. This allows an entire Root or Folder to be set Online or Offline (as opposed to individual root / folder targets which can already be set Online or Offline using TargetState on both resources.)

#### This Pull Request (PR) fixes the following issues

None

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/DFSDsc/133)

### CODE REVIEW

**Comment by johlju** [comment]
Please update this line to `windows-latest` then the build pipeline will run.

https://github.com/dsccommunity/DFSDsc/blob/990668d1ea9ce1c43647076ba473f02dd0f5631c/azure-pipelines.yml#L27

**Comment by Borgquite** [comment]
@johlju Done!

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 12 of 13 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DFSDsc/133)* status: 13 of 14 files reviewed, 6 unresolved discussions (waiting on @Borgquite)

___
*[`source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1` line 53 at r3](https://reviewable.io/reviews/dsccommunity/DFSDsc/133#-Nqczv1h8UMt2QmofeT_:-Nqczv1h8UMt2QmofeTa:b-95nsbj) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/3f3d89d8fed6404c4e5c4f569fc505317e3fc52c/source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1#L53)):*
> ```PowerShell
> 
>         [Parameter()]
>         [ValidateSet('Offline','Online')]
> ```

The parameter is not necessary in Get-TargetResource sinceit is not used.
___
*[`source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1` line 250 at r3](https://reviewable.io/reviews/dsccommunity/DFSDsc/133#-Nqd0ykF5kluqC0n49rI:-Nqd0ykF5kluqC0n49rJ:b-se4gk0) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/3f3d89d8fed6404c4e5c4f569fc505317e3fc52c/source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1#L250)):*
> ```PowerShell
> 
>             # Check the target properties
>             if (($State) `
> ```

The current implementation will make it a breaking change. :thinking:  Before, if a folder was set offline it was never enforced to online since the State was not enforced, but it was always set to online if one other property was needed to be enforced/changed. We could say that was a "bug"? 

Suggest removing the default value for the `State` property and only enforce `State` if it is passed in the configuration (e.g. `$PSBoundParameters.ContainsKey('State')`). This will still somewhat be a breaking change but fix the "bug" that was there before, so suggest not labeling and bumping major as we are more fixing a bug. :thinking: 

What do you think? (would be the same for the other resource too)
___
*[`source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1` line 553 at r3](https://reviewable.io/reviews/dsccommunity/DFSDsc/133#-Nqd40fm0hiuw5yJevLd:-Nqd40fm0hiuw5yJevLe:b-9zjbnp) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/3f3d89d8fed6404c4e5c4f569fc505317e3fc52c/source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1#L553)):*
> ```PowerShell
>             # Check the Namespace parameters
>             if (($State) `
>                 -and ($folder.State -ne $State))
> ```

This is a breaking change. It should only enforce `State` if passed in the configuration. The default value is not needed in Test-TargetResource.
___
*[`source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1` line 61 at r3](https://reviewable.io/reviews/dsccommunity/DFSDsc/133#-Nqd-KI86ozbo2owmQ9o:-Nqd-KI86ozbo2owmQ9p:b-p83z3v) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/3f3d89d8fed6404c4e5c4f569fc505317e3fc52c/source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1#L61)):*
> ```PowerShell
> 
>         [Parameter()]
>         [ValidateSet('Offline','Online')]
> ```

The parameter is not necessary in Get-TargetResource since it is not used.
___
*[`source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1` line 291 at r3](https://reviewable.io/reviews/dsccommunity/DFSDsc/133#-Nqd3EQGA1CVFz5ESVXG:-Nqd3EQGA1CVFz5ESVXH:b-6ol51x) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/3f3d89d8fed6404c4e5c4f569fc505317e3fc52c/source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1#L291)):*
> ```PowerShell
> 
>             # Check the target properties
>             if (($State) `
> ```

See comment in other resource about enforcing State.
___
*[`source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1` line 660 at r3](https://reviewable.io/reviews/dsccommunity/DFSDsc/133#-Nqd3fxbAM9rJIriaQOO:-Nqd3fxbAM9rJIriaQOP:b-9zjbnp) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/3f3d89d8fed6404c4e5c4f569fc505317e3fc52c/source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1#L660)):*
> ```PowerShell
> 
>             # Check the Namespace parameters
>             if (($State) `
> ```

This is a breaking change. It should only enforce `State` if passed in the configuration. The default value is not needed in Test-TargetResource.

**Review by Borgquite — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DFSDsc/133)* status: 12 of 14 files reviewed, 6 unresolved discussions (waiting on @johlju)

___
*[`source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1` line 53 at r3](https://reviewable.io/reviews/dsccommunity/DFSDsc/133#-Nqczv1h8UMt2QmofeT_:-NqgeuGa0_lvKS0mffgY:b-896fix) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/3f3d89d8fed6404c4e5c4f569fc505317e3fc52c/source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1#L53)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

The parameter is not necessary in Get-TargetResource sinceit is not used.
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1` line 250 at r3](https://reviewable.io/reviews/dsccommunity/DFSDsc/133#-Nqd0ykF5kluqC0n49rI:-NqgfNFX7SDClU7FzwQu:b-gdye04) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/3f3d89d8fed6404c4e5c4f569fc505317e3fc52c/source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1#L250)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

The current implementation will make it a breaking change. :thinking:  Before, if a folder was set offline it was never enforced to online since the State was not enforced, but it was always set to online if one other property was needed to be enforced/changed. We could say that was a "bug"? 

Suggest removing the default value for the `State` property and only enforce `State` if it is passed in the configuration (e.g. `$PSBoundParameters.ContainsKey('State')`). This will still somewhat be a breaking change but fix the "bug" that was there before, so suggest not labeling and bumping major as we are more fixing a bug. :thinking: 

What do you think? (would be the same for the other resource too)
</blockquote></details>

I hear you - what about TargetState though? At present the two fields work the same. I feel like it would be good to retain that. Should we remove the default value for both - that would be the least 'breaking' behavior and only impact systems if they for some reasons relied on the previous, undocumented behaviour?
___
*[`source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1` line 553 at r3](https://reviewable.io/reviews/dsccommunity/DFSDsc/133#-Nqd40fm0hiuw5yJevLd:-NqgfyR1-BulJNuwuNqV:ba7l58g) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/3f3d89d8fed6404c4e5c4f569fc505317e3fc52c/source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1#L553)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This is a breaking change. It should only enforce `State` if passed in the configuration. The default value is not needed in Test-TargetResource.
</blockquote></details>

Again, matches the TargetState behaviour. Same fix?
___
*[`source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1` line 61 at r3](https://reviewable.io/reviews/dsccommunity/DFSDsc/133#-Nqd-KI86ozbo2owmQ9o:-Nqgg6TD1u25IkkTKy5g:b-896fix) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/3f3d89d8fed6404c4e5c4f569fc505317e3fc52c/source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1#L61)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

The parameter is not necessary in Get-TargetResource since it is not used.
</blockquote></details>

Done.
___
*[`source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1` line 291 at r3](https://reviewable.io/reviews/dsccommunity/DFSDsc/133#-Nqd3EQGA1CVFz5ESVXG:-Nqgg76q7ogdv-nQd9NY:b-475rfi) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/3f3d89d8fed6404c4e5c4f569fc505317e3fc52c/source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1#L291)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

See comment in other resource about enforcing State.
</blockquote></details>

See comment :)
___
*[`source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1` line 660 at r3](https://reviewable.io/reviews/dsccommunity/DFSDsc/133#-Nqd3fxbAM9rJIriaQOO:-Nqgg8Pc4MKKiEQBR7Jt:b-475rfi) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/3f3d89d8fed6404c4e5c4f569fc505317e3fc52c/source/DSCResources/DSC_DFSNamespaceRoot/DSC_DFSNamespaceRoot.psm1#L660)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

This is a breaking change. It should only enforce `State` if passed in the configuration. The default value is not needed in Test-TargetResource.
</blockquote></details>

See comment :)

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/DFSDsc/133#-:-NqhxB9a-Dz64CkG_rGq:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Borgquite)

___
*[`source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1` line 250 at r3](https://reviewable.io/reviews/dsccommunity/DFSDsc/133#-Nqd0ykF5kluqC0n49rI:-NqhwYUvAwIYKmnBwyQs:bef6bmg) ([raw file](https://github.com/dsccommunity/DFSDsc/blob/3f3d89d8fed6404c4e5c4f569fc505317e3fc52c/source/DSCResources/DSC_DFSNamespaceFolder/DSC_DFSNamespaceFolder.psm1#L250)):*
<details><summary><i>Previously, Borgquite (Chris Hill) wrote…</i></summary><blockquote>

I hear you - what about TargetState though? At present the two fields work the same. I feel like it would be good to retain that. Should we remove the default value for both - that would be the least 'breaking' behavior and only impact systems if they for some reasons relied on the previous, undocumented behaviour?
</blockquote></details>

Yes, I good with fixing it the way you suggest. Good catch! :slightly_smiling_face:

**Comment by johlju** [comment]
@Borgquite awesome work on these PR's! Thank you! 😄

**Comment by Borgquite** [comment]
@johlju You're welcome! Just tried the preview release & looks OK to me - when you're ready for a full deploy!

**Comment by Borgquite** [comment]
@johlju As mentioned the preview release works fine on my system - can we do a full release? :) Many thanks!

**Comment by johlju** [comment]
Been on my todo list for a while, just haven't gotten around to it due to work and family commitments. 🙂

**Pull request merged**
