### PR TITLE
BREAKING CHANGE: xDFS renamed to DFSDsc: Renamed all DSCResources, Examples, Modules and Tests where applicable

### LINKED ISSUE #55: Convert Module Name to DFSDsc
As per recent DSC Resource Naming guidelines changes:
https://github.com/PowerShell/DscResources/blob/master/Naming.md

### PR DESCRIPTION
**Pull request by timhaintz**
**Pull Request (PR) description**

**This Pull Request (PR) fixes the following issues:**

**Task list:**
- [x ] Change details added to Unreleased section of CHANGELOG.md?
- [x ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [x ] Examples appropriately updated?
- [x ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xdfs/57)

### CODE REVIEW

**Comment by timhaintz** [comment]
@PlagueHO let me know any updates you need.
Thanks, Tim.

**Comment by PlagueHO** [comment]
Thanks heaps @timhaintz - I really appreciate this - I'll get onto the review later on today!

**Comment by PlagueHO** [comment]
Hi @timhaintz - sorry this took so long (lots of other PR's I had to get through :cry:).

It looks like the folders in `Modules/DFSDsc/Examples/Resources/` are named wrong - they shouldn't have `DFS` at the beginning - not `DFSDSC` . E.g. Modules/DFSDsc/Examples/Resources/DFSDscReplicationGroupMembership/2_Complete.ps1 -> Modules/DFSDsc/Examples/Resources/DFSReplicationGroupMembership/2_Complete.ps1. 

This is all looking pretty awesome! Just some minor tweaks around some changes from DFSDSC -> DFS.

I also noticed a few HQRM violations that I must have missed at some point (double quotes used when single quote should have been used). I've noted this so if you could correct those at the same time that would be awesome!

---

Reviewed 144 of 146 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 37 unresolved discussions.

---

*[CHANGELOG.md, line 6 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jESG7d2BkzctCOk92:-L4jESG7d2BkzctCOk93:b61ntqa) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/CHANGELOG.md#L6)):*
> ```Markdown
> 
> - BREAKING CHANGE
>   - Renamed xDFS to DFSDsc - fixes [Issue #55](https://github.com/PowerShell/xDFS/issues/55)
> ```

Needs a full stop.

---

*[CHANGELOG.md, line 7 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jEQLTA4yO84GA8VY-:-L4jEQLTA4yO84GA8VY0:b61ntqa) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/CHANGELOG.md#L7)):*
> ```Markdown
> - BREAKING CHANGE
>   - Renamed xDFS to DFSDsc - fixes [Issue #55](https://github.com/PowerShell/xDFS/issues/55)
>   - Changed all MSFT_xResourceName to MSFT_ResourceName
> ```

Needs a full stop.

---

*[CHANGELOG.md, line 10 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jEG22zef21Ch4Wvbv:-L4jEG22zef21Ch4Wvbw:b-x6lrhh) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/CHANGELOG.md#L10)):*
> ```Markdown
>   - Updated DSCResources, Examples, Modules and Tests for new naming.
>   - Updated Year to 2018 in License and Manifest.
> ```

Can you remove this blank line? I think otherwise it might upset the release note generation during the release process.

---

*[Modules/DFSDsc/DFSDsc.psd1, line 66 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jEqZSH61ufTpR7yWL:-L4jEqZSH61ufTpR7yWM:b-3on4bq) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Modules/DFSDsc/DFSDsc.psd1#L66)):*
> ```PowerShell
> - Replaced all type accelerators with full type names.
> - Updated Readme.md to contain resource list.
> - Fixed DFSDscNamespaceServerConfiguration by converting LocalHost to ComputerName
> ```

Can you revert this one? This bit gets auto-generated by the release process.

---

*[Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1, line 141 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jG1ImF3eipBewS8V1:-L4jG1ImF3eipBewS8V2:b-m6lzuk) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1#L141)):*
> ```PowerShell
>     parameter and should be set in th same order. If any entry is not blank
>     then the Content Paths will need to be set manually by
>     using the DFSDscReplicationGroupMembership resource.
> ```

DFSDscReplicationGroupMembership  -> DFSReplicationGroupMembership 

---

*[Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1, line 521 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jGA2RXBqplFxbzhhw:-L4jGA2RXBqplFxbzhhx:b-fs8f3k) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1#L521)):*
> ```PowerShell
>     parameter and should be set in th same order. If any entry is not blank
>     then the Content Paths will need to be set manually by
>     using the DFSDscReplicationGroupMembership resource.
> ```

DFSDscReplicationGroupMembership -> DFSReplicationGroupMembership

---

*[Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.schema.mof, line 10 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jGJiLo44-3M9l37nP:-L4jGJiLo44-3M9l37nQ:b-fs8f3k) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.schema.mof#L10)):*
> ```
>     [Write, Description("A list of folders that are replicated in this Replication Group.")] String Folders[];
>     [Write, Description("This allows a replication topology to assign to the Replication Group. It defaults to Manual, which will not automatically create a topology. If set to Fullmesh, a full mesh topology between all members will be created."), ValueMap{"Fullmesh","Manual"}, Values{"Fullmesh","Manual"}] String Topology;
>     [Write, Description("An array of DFS Replication Group Content Paths to use for each of the Folders. This can have one entry for each Folder in the Folders parameter and should be set in th same order. If any entry is not blank then the Content Paths will need to be set manually by using the DFSDscReplicationGroupMembership resource.")] String ContentPaths[];
> ```

DFSDscReplicationGroupMembership -> DFSReplicationGroupMembership

---

*[Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/README.md, line 5 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jGPiEoJ8c64zZ4snA:-L4jGPiEoJ8c64zZ4snB:bop160q) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/README.md#L5)):*
> ```Markdown
> This resource is used to create, edit or remove DFS Replication Groups. If used
> to create a Replication Group it should be combined with the
> DFSDscReplicationGroupMembership resources.
> ```

DFSDscReplicationGroupMembership -> DFSReplicationGroupMembership

---

*[Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroupFolder/README.md, line 11 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jGptMx-0OO62Xppuw:-L4jGptMx-0OO62Xppux:bum8osw) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroupFolder/README.md#L11)):*
> ```Markdown
> - DirectoryNameToExclude
> 
> In most cases just setting the Folders property in the DFSDscReplicationGroup
> ```

DFSDscReplicationGroup -> DFSReplicationGroup

---

*[Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroupMembership/README.md, line 7 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jH1XQsQAlSxAJILHU:-L4jH1XQsQAlSxAJILHV:bum8osw) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroupMembership/README.md#L7)):*
> ```Markdown
> Member computer. It can also be used to set additional properties of the Membership.
> This resource shouldn't be used for folders where the Content Path is set in the
> DFSDscReplicationGroup.
> ```

DFSDscReplicationGroup -> DFSReplicationGroup

---

*[Tests/Unit/MSFT_DFSNamespaceFolder.Tests.ps1, line 92 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJRqTcFSwdKgpFGR0:-L4jJRqUHl-SVrv_YZYC:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSNamespaceFolder.Tests.ps1#L92)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSNamespaceFolder\Get-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSNamespaceFolder.Tests.ps1, line 157 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJ_V3Gk4_sY7TJ9u9:-L4jJ_V3Gk4_sY7TJ9uA:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSNamespaceFolder.Tests.ps1#L157)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSNamespaceFolder\Set-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSNamespaceFolder.Tests.ps1, line 415 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJaHaZIhaHHiO8DS3:-L4jJaHaZIhaHHiO8DS4:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSNamespaceFolder.Tests.ps1#L415)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSNamespaceFolder\Test-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSNamespaceFolder.Tests.ps1, line 590 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJauoMlrQQEqH50TU:-L4jJauoMlrQQEqH50TV:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSNamespaceFolder.Tests.ps1#L590)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSNamespaceFolder\Get-Folder" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSNamespaceFolder.Tests.ps1, line 631 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJbgQdGW4EZgrB6mV:-L4jJbgQdGW4EZgrB6mW:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSNamespaceFolder.Tests.ps1#L631)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSNamespaceFolder\Get-FolderTarget" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSNamespaceRoot.Tests.ps1, line 103 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJf8fCmnUvk_I2P9o:-L4jJf8fCmnUvk_I2P9p:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSNamespaceRoot.Tests.ps1#L103)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSNamespaceRoot\Get-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSNamespaceRoot.Tests.ps1, line 105 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJg7yRZncFfaHs0OC:-L4jJg7yRZncFfaHs0OD:b485hfp) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSNamespaceRoot.Tests.ps1#L105)):*
> ```PowerShell
>         Describe "MSFT_DFSNamespaceRoot\Get-TargetResource" {
>             Context 'Namespace Root does not exist' {
> ```

Can you remove this blank line (I shouldn't have put it here)?

---

*[Tests/Unit/MSFT_DFSNamespaceRoot.Tests.ps1, line 178 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJjfKqCVgPE2CCaUB:-L4jJjfKqCVgPE2CCaUC:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSNamespaceRoot.Tests.ps1#L178)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSNamespaceRoot\Set-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSNamespaceRoot.Tests.ps1, line 505 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJkKm-zXuupaesiH8:-L4jJkKm-zXuupaesiH9:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSNamespaceRoot.Tests.ps1#L505)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSNamespaceRoot\Test-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSNamespaceRoot.Tests.ps1, line 748 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJku0O-qFNyibWAYe:-L4jJku14NSjOwVHaHSN:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSNamespaceRoot.Tests.ps1#L748)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSNamespaceRoot\Get-Root" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSNamespaceRoot.Tests.ps1, line 787 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJlVg9Mg0FO_oGzEN:-L4jJlVg9Mg0FO_oGzEO:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSNamespaceRoot.Tests.ps1#L787)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSNamespaceRoot\Get-RootTarget" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSNamespaceServerConfiguration.Tests.ps1, line 68 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJo_9K-JaiukVxvWa:-L4jJo_9K-JaiukVxvWb:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSNamespaceServerConfiguration.Tests.ps1#L68)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSNamespaceServerConfiguration\Get-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSNamespaceServerConfiguration.Tests.ps1, line 85 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJp772OR_BG_4QBRK:-L4jJp772OR_BG_4QBRL:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSNamespaceServerConfiguration.Tests.ps1#L85)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSNamespaceServerConfiguration\Set-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSNamespaceServerConfiguration.Tests.ps1, line 149 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJplhuygqhT_IS6nq:-L4jJplhuygqhT_IS6nr:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSNamespaceServerConfiguration.Tests.ps1#L149)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSNamespaceServerConfiguration\Test-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSReplicationGroup.Tests.ps1, line 214 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJsDI0sPqFps50fN0:-L4jJsDI0sPqFps50fN1:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSReplicationGroup.Tests.ps1#L214)):*
> ```PowerShell
>         $replicationGroupContentPath += @{ ContentPaths = @($mockReplicationGroupMembership.ContentPath) }
> 
>         Describe "MSFT_DFSReplicationGroup\Get-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSReplicationGroup.Tests.ps1, line 273 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJsojD90apqHi5-hx:-L4jJsojD90apqHi5-hy:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSReplicationGroup.Tests.ps1#L273)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSReplicationGroup\Set-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSReplicationGroup.Tests.ps1, line 927 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJtQxHgXxe-otOHyE:-L4jJtQxHgXxe-otOHyF:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSReplicationGroup.Tests.ps1#L927)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSReplicationGroup\Test-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSReplicationGroup.Tests.ps1, line 1287 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJuAkQ15ru3pKp07B:-L4jJuAkQ15ru3pKp07C:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSReplicationGroup.Tests.ps1#L1287)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSReplicationGroup\Get-FQDNMemberName" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSReplicationGroupConnection.Tests.ps1, line 115 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJw8XuBvsNjxc8G6A:-L4jJw8XuBvsNjxc8G6B:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSReplicationGroupConnection.Tests.ps1#L115)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSReplicationGroupConnection\Get-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSReplicationGroupConnection.Tests.ps1, line 184 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJwfIrqArOMczvxyt:-L4jJwfIrqArOMczvxyu:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSReplicationGroupConnection.Tests.ps1#L184)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSReplicationGroupConnection\Set-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSReplicationGroupConnection.Tests.ps1, line 362 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJxGSfTMtZ0u61uOy:-L4jJxGSfTMtZ0u61uOz:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSReplicationGroupConnection.Tests.ps1#L362)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSReplicationGroupConnection\Test-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSReplicationGroupFolder.Tests.ps1, line 99 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJylaTdkcOYxdTnxN:-L4jJylaTdkcOYxdTnxO:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSReplicationGroupFolder.Tests.ps1#L99)):*
> ```PowerShell
>         )
> 
>         Describe "MSFT_DFSReplicationGroupFolder\Get-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSReplicationGroupFolder.Tests.ps1, line 146 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJzErT_RzZ7mo9VRA:-L4jJzErT_RzZ7mo9VRB:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSReplicationGroupFolder.Tests.ps1#L146)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSReplicationGroupFolder\Set-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSReplicationGroupFolder.Tests.ps1, line 204 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jJzoSJdHeMBm-BYvk:-L4jJzoSJdHeMBm-BYvl:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSReplicationGroupFolder.Tests.ps1#L204)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSReplicationGroupFolder\Test-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSReplicationGroupMembership.Tests.ps1, line 90 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jK0D8P2RP4GD94O8h:-L4jK0D8P2RP4GD94O8i:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSReplicationGroupMembership.Tests.ps1#L90)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSReplicationGroupMembership\Get-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSReplicationGroupMembership.Tests.ps1, line 163 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jK0eeQ6v2Rb9u3D5v:-L4jK0eeQ6v2Rb9u3D5w:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSReplicationGroupMembership.Tests.ps1#L163)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSReplicationGroupMembership\Set-TargetResource"{
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---

*[Tests/Unit/MSFT_DFSReplicationGroupMembership.Tests.ps1, line 254 at r2](https://reviewable.io:443/reviews/powershell/xdfs/57#-L4jK1J7gWP_YQVe_GE6:-L4jK1J7gWP_YQVe_GE7:bgcd4gy) ([raw file](https://github.com/powershell/xdfs/blob/7a8eb618132e95cb2b6df41033da5fac08ae2b5a/Tests/Unit/MSFT_DFSReplicationGroupMembership.Tests.ps1#L254)):*
> ```PowerShell
>         }
> 
>         Describe "MSFT_DFSReplicationGroupMembership\Test-TargetResource" {
> ```

Could you do me a favor and change the double quotes to single quotes for me (I must have missed this one at some point)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/57#-:-L4jHJGpPVWRqEuOXy_s:b-iajogv)*

**Comment by PlagueHO** [comment]
Oh, and once you made the changes and comited them to the PR, go in to AppVeyor and click Done against each issue you've resolved. That will make it easy for me to Acknowledge each one.

---

Review status: all files reviewed at latest revision, 37 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/57#-:-L4jKPe4hamA0Rwb9mrM:bthjax6)*

**Comment by timhaintz** [comment]
No worries at all, I'm sure you have plenty of things on!
I knew I would miss some DFSDsc ones. Thanks for picking them up. Will go through tonight and update. Cheers.

**Comment by timhaintz** [comment]
@PlagueHO all updated. I think I have done the Reviewable bit too. I acknowledged all that I updated. Still new though so I'm not sure I did it correctly?
Thanks for all your help with this. You have a very keen eye! I thought I got most of DFSDsc ones correct!
Thanks! 👍

**Comment by PlagueHO** [comment]
Hi @timhaintz

I think you might have not pushed Publish in Reviewable after clicking "Done" on all the issues. Clicking Done causes all your comments to be rolled up for me into a single response. I can then click through each one validating it. No worries though - I can still acknowledge them (just takes 2 clicks instead of one :grin: ). And don't worry, you'll get used to the whole process - it takes a while to get all the bits down (I've been at this a few years and still forget bits :grin:)

Anyway, :lgtm:

@kwirkykat - are you able to perform the rename of this repo so I can merge this PR?

---

Reviewed 30 of 163 files at r1, 48 of 48 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/57#-:-L4tTGqU4_oaV2kBsSYA:b-slzkbe)*

**Comment by timhaintz** [comment]
Argh!!! Sorry!!! I knew I needed to do that too. Thanks for your patience. 🥇

**Comment by PlagueHO** [comment]
No worries @timhaintz - again, thanks for your help :grin: everyone gotta start somewhere!

**Comment by PlagueHO** [comment]
@kwirkykat - sorry, I forgot to message you about this one. Are you able to rename this repo if you're happy?

**Comment by kwirkykat** [comment]
@PlagueHO Done

**Comment by PlagueHO** [comment]
Thankyou @kwirkykat

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/57#-:-LB-uKijDmcSw33e3uC2:blb335t)*

**Comment by PlagueHO** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/57#-:-LB-uTeY0UaYuHrK_MqT:bnfp4nl)*

**Comment by johlju** [comment]
@PlagueHO Can you send in a PR to DscResource and update the name there as well (switch submodules folders)?

**Comment by PlagueHO** [comment]
Done - in my existing PR adding the submodules

**Pull request merged**
