### PR TITLE
DFSReplicationGroup: fix for null compare-object error

### LINKED ISSUE #27: xDFSReplicationGroup - Error while comparing array containing $null
In xDFSReplicationGroup `Test-TargetResource` the following code can set `$ExistingFolders` to a `@($null)` array when the replication group does not yet contain folders. This results in a `ParameterBindingValidation` exception while subsequently evaluating the Compare-Object just below it.

```
# Compare the Folders
$ExistingFolders = @((Get-DfsReplicatedFolder @Splat -ErrorAction Stop).FolderName)
if ((Compare-Object `
    -ReferenceObject $Folders `
    -DifferenceObject $ExistingFolders).Count -ne 0)
```

Error message;
```
Compare-Object : Cannot bind argument to parameter 'ReferenceObject' because it is null.
    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParameterBindingValidation
   Exception
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.Powe
   rShell.Commands.CompareObjectCommand
```

Can be resolved with:
`$ExistingFolders = @((Get-DfsReplicatedFolder @Splat -ErrorAction Stop).FolderName) | where { $_ -ne $null }`

### PR DESCRIPTION
**Pull request by murrahjm**
**Pull Request (PR) description**
Add section to check for null values in existing member list or proposed member list before using compare-object.  Also added same logic to the comparison of existing and proposed folder list.

**This Pull Request (PR) fixes the following issues:**
Fixes #27 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [x] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/63)

### CODE REVIEW

**Comment by johlju** [comment]
Could you resolve the lint errors in the README.md line 5 (line too long).
https://ci.appveyor.com/project/PowerShell/dfsdsc/build/3.1.7.0#L1425

**Comment by PlagueHO** [comment]
Ok, I've got my lab up now and so I can begin running the manual integration tests on your change. Shouldn't be long now! Sorry it took so long.

**Comment by PlagueHO** [comment]
Would it be possible to add some unit tests for the new conditions?

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[CHANGELOG.md, line 5 at r2](https://reviewable.io/reviews/powershell/dfsdsc/63#-LD5l6bz3R-dTlHHhrQp:-LD5l6bz3R-dTlHHhrQq:b-q14vkw) ([raw file](https://github.com/powershell/dfsdsc/blob/a4e25f982d5b51ab95e7dfb50d8d1e8c4af51eeb/CHANGELOG.md#L5)):*
> ```Markdown
> ## Unreleased
> 
> - Resolved issue with null values in resource group members or folders.
> ```

Can you add ` - fixes [Issue #62](https://github.com/PowerShell/xDFS/issues/62).` to the end of this line?

---

*[Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1, line 629 at r2](https://reviewable.io/reviews/powershell/dfsdsc/63#-LD5lLxk1Cac7ArrsS5k:-LD5lLxk1Cac7ArrsS5l:bb80hgs) ([raw file](https://github.com/powershell/dfsdsc/blob/a4e25f982d5b51ab95e7dfb50d8d1e8c4af51eeb/Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1#L629)):*
> ```PowerShell
>             # Compare the Members
>             $existingMembers = @((Get-DfsrMember @replicationGroupParameters -ErrorAction Stop).DnsName)
>             #check for null values before using compare-object
> ```

Can you convert block comments like this:
```powershell
<#
    check for null values before using compare-object
    if one is null but not both then report difference
    if neither are null then compare values
#>
```

And throughout

---

*[Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1, line 632 at r2](https://reviewable.io/reviews/powershell/dfsdsc/63#-LD5lbpjAtXo4KNoXwbP:-LD5lbpjAtXo4KNoXwbQ:bj3t9vt) ([raw file](https://github.com/powershell/dfsdsc/blob/a4e25f982d5b51ab95e7dfb50d8d1e8c4af51eeb/Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1#L632)):*
> ```PowerShell
>             # if one is null but not both then report difference
>             # if neither are null then compare values
>             if ([String]::IsNullOrEmpty($existingMembers) -and [String]::IsNullOrEmpty($fqdnMembers)) {
> ```

} and { for if blocks need to be on their own line

And throughout

---

*[Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1, line 633 at r2](https://reviewable.io/reviews/powershell/dfsdsc/63#-LD5liIX36ROwEZ1fbf7:-LD5liIZ1uCXrq7efWWV:bf8ndw1) ([raw file](https://github.com/powershell/dfsdsc/blob/a4e25f982d5b51ab95e7dfb50d8d1e8c4af51eeb/Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1#L633)):*
> ```PowerShell
>             # if neither are null then compare values
>             if ([String]::IsNullOrEmpty($existingMembers) -and [String]::IsNullOrEmpty($fqdnMembers)) {
>                 #both are null so no difference found
> ```

Can you add space between # and both?

---

*[Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1, line 634 at r2](https://reviewable.io/reviews/powershell/dfsdsc/63#-LD5ll1o18kzZBu0a4h_:-LD5ll1o18kzZBu0a4ha:bj3t9vt) ([raw file](https://github.com/powershell/dfsdsc/blob/a4e25f982d5b51ab95e7dfb50d8d1e8c4af51eeb/Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1#L634)):*
> ```PowerShell
>             if ([String]::IsNullOrEmpty($existingMembers) -and [String]::IsNullOrEmpty($fqdnMembers)) {
>                 #both are null so no difference found
>             } elseif ([String]::IsNullOrEmpty($existingMembers) -xor [String]::IsNullOrEmpty($fqdnMembers)) {
> ```

} and { for if blocks need to be on their own line

And throughout

---

*[Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1, line 644 at r2](https://reviewable.io/reviews/powershell/dfsdsc/63#-LD5lv-ZEjHph5C2YpGx:-LD5lv-ZEjHph5C2YpGy:b-prgxt3) ([raw file](https://github.com/powershell/dfsdsc/blob/a4e25f982d5b51ab95e7dfb50d8d1e8c4af51eeb/Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1#L644)):*
> ```PowerShell
>                 $desiredConfigurationMatch = $false
>             }  else {
>                 #neither variables are null so it's safe to use compare-object
> ```

Can you add space between # and neither?

---

*[Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1, line 665 at r2](https://reviewable.io/reviews/powershell/dfsdsc/63#-LD5m-af-EKT5XoXuLKO:-LD5m-af-EKT5XoXuLKP:b-8cx3s9) ([raw file](https://github.com/powershell/dfsdsc/blob/a4e25f982d5b51ab95e7dfb50d8d1e8c4af51eeb/Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1#L665)):*
> ```PowerShell
>             # if one is null but not both then report difference
>             # if neither are null then compare values
>             if ([String]::IsNullOrEmpty($existingFolders) -and [String]::IsNullOrEmpty($Folders)){
> ```

} and { for if blocks need to be on their own line

---

*[Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1, line 666 at r2](https://reviewable.io/reviews/powershell/dfsdsc/63#-LD5m3a21HinaY-n3kDQ:-LD5m3a21HinaY-n3kDR:bf8ndw1) ([raw file](https://github.com/powershell/dfsdsc/blob/a4e25f982d5b51ab95e7dfb50d8d1e8c4af51eeb/Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1#L666)):*
> ```PowerShell
>             # if neither are null then compare values
>             if ([String]::IsNullOrEmpty($existingFolders) -and [String]::IsNullOrEmpty($Folders)){
>                 #both are null so no difference found
> ```

Can you add space between # and both?

---

*[Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1, line 677 at r2](https://reviewable.io/reviews/powershell/dfsdsc/63#-LD5m4OZEYaXvAQ_gH4y:-LD5m4O_2-Pkahh3-uMD:b-prgxt3) ([raw file](https://github.com/powershell/dfsdsc/blob/a4e25f982d5b51ab95e7dfb50d8d1e8c4af51eeb/Modules/DFSDsc/DSCResources/MSFT_DFSReplicationGroup/MSFT_DFSReplicationGroup.psm1#L677)):*
> ```PowerShell
>                 $desiredConfigurationMatch = $false
>             } else {
>                 #neither variables are null so it's safe to use compare-object
> ```

Can you add space between # and neither?

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/63#-:-LD5mMsXBunOq27DzLRX:b59ewrp)*

**Comment by PlagueHO** [comment]
Ok @murrahjm - I've tested your patch and it looks great. All the integration tests and unit tests still pass. But it would be good to get some additional unit tests to cover the new code path.

So once this is done and the other style corrections then we're good to go. Thank you again for resolving this.

---

Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/63#-:-LD6Mc796g2MiQCQre_l:bvayqc8)*

**Comment by PlagueHO** [comment]
Hi @murrahjm - there is a branch conflict caused by the other PR's that merged. Could you resolve?

**Comment by murrahjm** [comment]
Added some unit tests.  Not sure how to run those locally to verify that they're good, but I think I was able to replicate the pattern you have with the other tests.  they should test these scenarios:

- Replication group with members tested against setting with no members
- Replication group with no members tested against setting with no members
- Replication group with folders tested against setting with no folders
- Replication group with no folders tested against setting with no folders

**Comment by PlagueHO** [comment]
Just a couple of really tiny corrections to the tests and then I'll merge - great stuff @murrahjm.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_DFSReplicationGroup.Tests.ps1, line 1022 at r3](https://reviewable.io/reviews/powershell/dfsdsc/63#-LDuHN6ICzrN5YiT7HnS:-LDuHN6K0cd_bBXBo27r:b-mu7lvk) ([raw file](https://github.com/powershell/dfsdsc/blob/de481b6f9c17a3e66263d6dd31edb414ea4501c6/Tests/Unit/MSFT_DFSReplicationGroup.Tests.ps1#L1022)):*
> ```PowerShell
>                 Mock Get-DfsReplicatedFolder -MockWith { return $mockReplicationGroupFolder }
> 
>                 It 'Should return false' {
> ```

I think this should read: 'Should return true'

---

*[Tests/Unit/MSFT_DFSReplicationGroup.Tests.ps1, line 1144 at r3](https://reviewable.io/reviews/powershell/dfsdsc/63#-LDuHSmJ7aFvRL6Wh-Sb:-LDuHSmJ7aFvRL6Wh-Sc:b-mu7lvk) ([raw file](https://github.com/powershell/dfsdsc/blob/de481b6f9c17a3e66263d6dd31edb414ea4501c6/Tests/Unit/MSFT_DFSReplicationGroup.Tests.ps1#L1144)):*
> ```PowerShell
>                 Mock Get-DfsReplicatedFolder -MockWith { return $null }
> 
>                 It 'Should return false' {
> ```

I think this should read: 'Should return true'

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/63#-:-LDuHfH1C6gGLGhOQPZM:b-m3j44c)*

**Comment by PlagueHO** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/63#-:-LDx2uCA6EdHtbBHsSc2:bnfp4nl)*

**Pull request merged**
