### PR TITLE
Correct style violations in If block braces - Fixes #84

### LINKED ISSUE #84: Correct If Brace Style in Resource to resolve PSSA Style Violations
#### Details of the scenario you tried and the problem that is occurring

PSSA style rule checks are failing due to incorrect if block style:
https://ci.appveyor.com/project/PlagueHO/dfsdsc#L567

#### Verbose logs showing the problem

N/A

#### Suggested solution to the issue

Correct the style.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)

N/A

#### The operating system the target node is running

N/A

#### Version and build of PowerShell the target node is running

N/A

#### Version of the DSC module that was used ('dev' if using current dev branch)

N/A

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR fixes style violations in If block braces.

#### This Pull Request (PR) fixes the following issues

- Fixes #84 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju - would you mind reviewing this one? It should be pretty simple as it is just a style correction.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/85)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@Johlju - I moved the location of the CHANGELOG.MD entry into the 4.3.0.0 block because the release is currently in progress/on-hold.

**Comment by PlagueHO** [comment]
Hi @johlju - are you able to review this one for me? Hopefully just a simple style correction to unblock the release.

**Review by johlju — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/85#-:-LXA4QwT3_5NQnrk5cx6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/85)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[CHANGELOG.md, line 8 at r1](https://reviewable.io/reviews/powershell/dfsdsc/85#-LXA4U6J3EbOOQrUTHt-:-LXA4U6J3EbOOQrUTHt0:b673vyv) ([raw file](https://github.com/powershell/dfsdsc/blob/968dca7c86528f0a1bbc2cbe17cc18e9d57234b4/CHANGELOG.md#L8)):*
> ```Markdown
> 
> - Explicitly removed extra hidden files from release package
> - Fixes PSSA style violation issues resulting - fixes [Issue #84](https://github.com/PowerShell/DfsDsc/issues/84).
> ```

Was to quick to hit LGTM. Missed that the change log entry did not move under the Unreleased section (probably when you rebased). :slightly_smiling_face:

**Review by PlagueHO — COMMENTED** [review]
Thanks again @Johlju

> *[Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/85#-:-LXAqIQa2W8pu4mKUGZl:b-7w4khq)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[CHANGELOG.md, line 8 at r1](https://reviewable.io/reviews/powershell/dfsdsc/85#-LXA4U6J3EbOOQrUTHt-:-LXAqH-DDwV4C75fbSOC:b-896fix) ([raw file](https://github.com/powershell/dfsdsc/blob/968dca7c86528f0a1bbc2cbe17cc18e9d57234b4/CHANGELOG.md#L8)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Was to quick to hit LGTM. Missed that the change log entry did not move under the Unreleased section (probably when you rebased). :slightly_smiling_face: 
</blockquote></details>

Done.

**Review by johlju — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/85#-:-LXDsMsuEht9QIuxDGGn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
