### PR TITLE
Release of version 4.3.0.0 of DFSDsc

### PR DESCRIPTION
**Pull request by kwirkykat**
Releasing version 4.3.0.0

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/83)

### CODE REVIEW

**Comment by kwirkykat** [comment]
@PlagueHO Looks like some recent changes have upset PSSA 🙁 If you or someone else wants to fix this, I can push this release out whenever these tests pass

**Comment by PlagueHO** [comment]
@kwirkykat - I suspect [this change](https://github.com/PowerShell/DscResource.Tests/pull/295) in DscResource.Tests may have caused false positive style violations. I'll see if I can get a change through to DscResource.Tests to resolve the problem at that side.

**Comment by PlagueHO** [comment]
@kwirkykat - Doh! No wait - it has totally picked up my style violation here! :cry: I got confused due to using different brace style rule at my day job! :grin:

**Comment by PlagueHO** [comment]
Once #85 is through then it should correct this problem.

**Comment by PlagueHO** [comment]
Not abandoned bot! :grin:

**Comment by PlagueHO** [comment]
Closing this and will revert release.

**Pull request closed without merging**
