### PR TITLE
Added Documentation and Examples section to README.MD - Fixes #49

### LINKED ISSUE #49: Link Readme.md to Wiki Entries
**Details of the scenario you tried and the problem that is occurring:**
It is not obvious from the README.MD that there is a Wiki containing the full documentation.

**The DSC configuration that is using the resource (as detailed as possible):**
N/A

**Version of the Operating System and PowerShell the DSC Target Node is running:**
N/A

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
N/A

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
Added Documentation and Examples section to README.MD. Wording mostly copied from SharePointDsc.

**This Pull Request (PR) fixes the following issues:**
Fixes #49 

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [ ] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xdfs/50)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@Johlju - would you mind reviewing when you get a chance?

**Comment by johlju** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 34 at r1](https://reviewable.io:443/reviews/powershell/xdfs/50#-KsTy_tvCZd_Ht1TiYz9:-KsTy_tvCZd_Ht1TiYzA:b-uwtvkd) ([raw file](https://github.com/powershell/xdfs/blob/fdba6a7fb3bcb783c92768274fe91009688fad9d/README.md#L34)):*
> en-US

Can't find a en-US folder in the root of xDFS...?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/50)*

**Comment by PlagueHO** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 34 at r1](https://reviewable.io:443/reviews/powershell/xdfs/50#-KsTy_tvCZd_Ht1TiYz9:-KsVLByqqmf71WZDyI3u:b-mym0xw) ([raw file](https://github.com/powershell/xdfs/blob/fdba6a7fb3bcb783c92768274fe91009688fad9d/README.md#L34)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> en-US

Can't find a en-US folder in the root of xDFS...?
</blockquote></details>

That is correct :grin: This folder gets created by the Autodocumenation code - so only exists in modules installed from the PS Gallery. I've changed the wording to better reflect this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/50)*

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 37 at r2](https://reviewable.io:443/reviews/powershell/xdfs/50#-KsZ2YAvuee9X1tjPeku:-KsZ2YAvuee9X1tjPekv:bn0bxdz) ([raw file](https://github.com/powershell/xdfs/blob/5cbe0110f8776883e104766068f49c6bd718c466/README.md#L37)):*
> ... the `en-US` directory in the contains locally ...

Look at rephrasing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/50)*

**Comment by PlagueHO** [comment]
@Johlju - Unfortunately it looks like the release process for the Autodocumentation resources is a bit broken (or a different process is used). I'll follow up with @KwirkyKat on this.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/50#-:-Ks_Q-qXdA7qlVrU-NNn:b-k0czcu)*

**Comment by PlagueHO** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 37 at r2](https://reviewable.io:443/reviews/powershell/xdfs/50#-KsZ2YAvuee9X1tjPeku:-Ksm5o6GhAFLktQMPJ9B:b-4n6zeb) ([raw file](https://github.com/powershell/xdfs/blob/5cbe0110f8776883e104766068f49c6bd718c466/README.md#L37)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ... the `en-US` directory in the contains locally ...

Look at rephrasing.
</blockquote></details>

I've removed this whole paragraph until I can implement a process to ensure this info is all being copied into the Resource Module during release.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/50)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/50#-:-KsnDCx1yuolBarKzM3z:bnfp4nl)*

**Pull request merged**
