### PR TITLE
BREAKING CHANGE; Update to new CD Pipeline - Fixes #98

### LINKED ISSUE #98: DFSDsc: Converting to new CI pipeline
Work need to be done to convert this repository to use the new CI pipeline.

https://dsccommunity.org/blog/convert-a-module-for-continuous-delivery/

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR updates the repo to the new CD Pipeline structure.

#### This Pull Request (PR) fixes the following issues

- Fixes #98 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju - would you mind reviewing for me please when you have time?

Only 2 more repos (of mine) to go after this one ;)

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/99)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 111 of 111 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/99)* status: all files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[azure-pipelines.yml, line 7 at r1](https://reviewable.io/reviews/dsccommunity/dfsdsc/99#-M5qQOIK4pt7uyWCsfyx:-M5qQOIK4pt7uyWCsfyy:bna5j7h) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/a01ea47dc4af6f9f3e385b91933c32655a3527ec/azure-pipelines.yml#L7)):*
> ```
> - source/**/*
> ```

This need to be `source/*` now. Something broke in Azure DevOps and the docs that mentioned this pattern no longer exist, we had to change it all over. :/ Using `**` will now make the pipeline to never run at all. This did work for about a week or two in ActiveDirectoryDsc. Now the docs read:

> You may not include * in the middle of a path filter, and you may not use ?.

https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#wildcards

https://github.com/dsccommunity/ActiveDirectoryDsc/pull/599
___
*[HISTORIC_CHANGELOG.md, line 1 at r1](https://reviewable.io/reviews/dsccommunity/dfsdsc/99#-M5qS6PwEAh7eYKUwir3:-M5qS6PwEAh7eYKUwir4:b-fs224) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/a01ea47dc4af6f9f3e385b91933c32655a3527ec/HISTORIC_CHANGELOG.md#L1)):*
> ```
> # Historic change log for DFSDsc
> ```

Non-blocking: In a recent fix in Sampler this file is no longer needed. All the changelog can now be in CHANGELOG.md. This file was a workaround for a bug that is now fixed. :) But if you want to leave it as-is that is fine. :)
___
*[RequiredModules.psd1, line 14 at r1](https://reviewable.io/reviews/dsccommunity/dfsdsc/99#-M5qSVbt-FM4Xt21qeS8:-M5qSVbt-FM4Xt21qeS9:bvgk1nb) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/a01ea47dc4af6f9f3e385b91933c32655a3527ec/RequiredModules.psd1#L14)):*
> ```
> '1.0.0'
> ```

Non-blocking: We can now use latest here. Sampler was fixed for this as well.
___
*[source/DFSDsc.psd1, line 66 at r1](https://reviewable.io/reviews/dsccommunity/dfsdsc/99#-M5qT1WLD64d88r9cKBW:-M5qT1WLD64d88r9cKBX:b-2i6wfx) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/a01ea47dc4af6f9f3e385b91933c32655a3527ec/source/DFSDsc.psd1#L66)):*
> ```PowerShell
>             # A URL to the main website for this project.
>             ProjectUri   = 'https://github.com/dsccommunity/DFSDsc'
> ```

Non-blocking: Do you want to add in the Icon url too?
___
*[source/DSCResources/DSC_DFSReplicationGroupMembership/DSC_DFSReplicationGroupMembership.psm1, line 3 at r1](https://reviewable.io/reviews/dsccommunity/dfsdsc/99#-M5qTcZ_DxGzCy61mUHH:-M5qTcZ_DxGzCy61mUHI:blgg3n4) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/a01ea47dc4af6f9f3e385b91933c32655a3527ec/source/DSCResources/DSC_DFSReplicationGroupMembership/DSC_DFSReplicationGroupMembership.psm1#L3)):*
> ```
> Import the Networking Common Modules
> ```

Maybe "...DFS Common module"?

**Review by PlagueHO — COMMENTED** [review]
Awesome catches @johlju - didn't know about the other recent changes to the pipeline (been working on a large Azure architecture project long hours and no spare time). I'll repeat all the changes in the other repos today. I also found I hadn't updated the Examples with the correct info when I moved project over to dsccommunity. So fixed that too.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/99#-:-M5sT_ye-z1ZHlkwQNza:b-q7oz53)* status: 85 of 110 files reviewed, 2 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[azure-pipelines.yml, line 7 at r1](https://reviewable.io/reviews/dsccommunity/dfsdsc/99#-M5qQOIK4pt7uyWCsfyx:-M5sMKAMAkLqthD_UNhz:b4dyz46) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/a01ea47dc4af6f9f3e385b91933c32655a3527ec/azure-pipelines.yml#L7)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> - source/**/*
> ```

This need to be `source/*` now. Something broke in Azure DevOps and the docs that mentioned this pattern no longer exist, we had to change it all over. :/ Using `**` will now make the pipeline to never run at all. This did work for about a week or two in ActiveDirectoryDsc. Now the docs read:

> You may not include * in the middle of a path filter, and you may not use ?.

https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#wildcards

https://github.com/dsccommunity/ActiveDirectoryDsc/pull/599
</blockquote></details>

Ah right OK. I'll need to go through and modify all my repos :) Might tag you in the PR's :grin:
___
*[HISTORIC_CHANGELOG.md, line 1 at r1](https://reviewable.io/reviews/dsccommunity/dfsdsc/99#-M5qS6PwEAh7eYKUwir3:-M5sRdchCiFpllrBb1JF:br99i3z) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/a01ea47dc4af6f9f3e385b91933c32655a3527ec/HISTORIC_CHANGELOG.md#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> # Historic change log for DFSDsc
> ```

Non-blocking: In a recent fix in Sampler this file is no longer needed. All the changelog can now be in CHANGELOG.md. This file was a workaround for a bug that is now fixed. :) But if you want to leave it as-is that is fine. :)
</blockquote></details>

I'll merge them - will go through and do all the others as well ;) Expect PR's :grin:

**Review by PlagueHO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/99)* status: 78 of 110 files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[source/DSCResources/DSC_DFSReplicationGroupMembership/DSC_DFSReplicationGroupMembership.psm1, line 3 at r1](https://reviewable.io/reviews/dsccommunity/dfsdsc/99#-M5qTcZ_DxGzCy61mUHH:-M5sUGNy5Dy-T3LC6_fA:b-896fix) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/a01ea47dc4af6f9f3e385b91933c32655a3527ec/source/DSCResources/DSC_DFSReplicationGroupMembership/DSC_DFSReplicationGroupMembership.psm1#L3)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> Import the Networking Common Modules
> ```

Maybe "...DFS Common module"?
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 33 of 33 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/99#-:-M5uUTdS0flBdnev4QyM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by johlju** [comment]
I hope the big project is working out well. :) Awesome work with all the PR's! All reviewed. 😄

**Comment by PlagueHO** [comment]
Thanks for all the reviews @johlju - we'll see how project is working out in the next few days ;)

**Pull request merged**
