### PR TITLE
Updated tests to meet Pester V4 guidelines - Fixes #53

### LINKED ISSUE #53: Migrate Pester Test Syntax from v3 -> v4
**Details of the scenario you tried and the problem that is occurring:**
As of Pester v4 the syntax of the `Should` cmdlet has changed from `Should Be` to `Should -Be`.

There is a helpful script that can be used to easily perform the conversion:
https://gist.github.com/indented-automation/aeb14825e39dd8849beee44f681fbab3

This script should be used to correct the Pester syntax.

### PR DESCRIPTION
**Pull request by PlagueHO**
**Pull Request (PR) description**
This PR updates the tests to meet Pester V4 guidelines.

**This Pull Request (PR) fixes the following issues:**
- Fixes #53

**Task list:**
- [x] Change details added to Unreleased section of CHANGELOG.md?
- [ ] Added/updated documentation, comment-based help and descriptions in .schema.mof files where appropriate?
- [ ] Examples appropriately updated?
- [ ] New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [x] [Unit and (optional) Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?

@johlju - would you mind reviewing? I am hoping this is trivial as it is just a Pester V3 -> V4 conversion. But no rush at all. As always I'm eternally grateful for all your help on these resources (seriously, I don't know how I'd get changes through without you).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xdfs/56)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@Johlju - I could have converted all the `It 'should` to `It 'Should` (capital S for should) but there were so many that I didn't want to make the diff that large. Happy to do it though if you want (as it is just a simple search/replace).

**Comment by johlju** [comment]
It’s okay by me if you want to do it. Will try to review the pending PRs tomorrow.

**Comment by PlagueHO** [comment]
Thanks @johlju - I did it to get it out of the way. Thanks again!

**Comment by johlju** [comment]
Reviewed 2 of 16 files at r1, 14 of 14 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xDFSNamespaceFolder.Tests.ps1, line 221 at r2](https://reviewable.io:443/reviews/powershell/xdfs/56#-L2pGoLUz4l-tldDQVYY:-L2pGoLUz4l-tldDQVYZ:b-6vod5q) ([raw file](https://github.com/powershell/xdfs/blob/a39fa61b124d8e4cb3a8bd28a80f6c64f0e4e7a5/Tests/Unit/MSFT_xDFSNamespaceFolder.Tests.ps1#L221)):*
> -Exactly 1

These should be `-Exactly -Times 1`. Throughout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/56)*

**Comment by PlagueHO** [comment]
Review status: 9 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Unit/MSFT_xDFSNamespaceFolder.Tests.ps1, line 221 at r2](https://reviewable.io:443/reviews/powershell/xdfs/56#-L2pGoLUz4l-tldDQVYY:-L2qAw3GDnZK4JSQuz1c:b-896fix) ([raw file](https://github.com/powershell/xdfs/blob/a39fa61b124d8e4cb3a8bd28a80f6c64f0e4e7a5/Tests/Unit/MSFT_xDFSNamespaceFolder.Tests.ps1#L221)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> -Exactly 1

These should be `-Exactly -Times 1`. Throughout.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/56)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/56#-:-L2qDUG5H2eEhaZTzHK4:bnfp4nl)*

**Pull request merged**
