### PR TITLE
Improve layout of badge area in README.MD - Fixes #41

### LINKED ISSUE #41: Improve Badge Area in README.MD to show table and both master/dev branches

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR puts the badges into a table and adds badges for both Dev and Master branches.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xdfs/42)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@johlju - any change you could review this one? Thanks again sir! :grin:

**Comment by johlju** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.markdownlint.json, line 4 at r2](https://reviewable.io:443/reviews/powershell/xdfs/42#-KpEeXPlBUn2q-bK1uPF:-KpEeXPlBUn2q-bK1uPG:bwvov2n) ([raw file](https://github.com/powershell/xdfs/blob/ae1280e0900c100d9ce7e0d658d58d3b18b439df/.markdownlint.json#L4)):*
> ```JSON
>     "default": true,
>     "MD029": {
>         "style": "ordered"
> ```

Should be "one" now.

---

*[README.md, line 3 at r2](https://reviewable.io:443/reviews/powershell/xdfs/42#-KpEeJYCoUJtvcD1VHAu:-KpEeJYCoUJtvcD1VHAv:b-figykc) ([raw file](https://github.com/powershell/xdfs/blob/ae1280e0900c100d9ce7e0d658d58d3b18b439df/README.md#L3)):*
> ```Markdown
> # xDFS
> 
> | Branch | Build Status | Code Coverage |
> ```

Suggest adding to headers instead (see comment in PR over at xStorage) so that MD013 can be enabled.
Example over at xSQLServer and xFailOverCluster.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/42)*

**Comment by PlagueHO** [comment]
All done! Thanks @johlju for the review - as always. And sorry about all the PR's - I'm on holiday so I'm trying to catch up on as much stuff as possible. 

---

Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[.markdownlint.json, line 4 at r2](https://reviewable.io:443/reviews/powershell/xdfs/42#-KpEeXPlBUn2q-bK1uPF:-KpHHlDOsLXFVtghSemo:b-896fix) ([raw file](https://github.com/powershell/xdfs/blob/ae1280e0900c100d9ce7e0d658d58d3b18b439df/.markdownlint.json#L4)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Should be "one" now.
</blockquote></details>

Done.

---

*[README.md, line 3 at r2](https://reviewable.io:443/reviews/powershell/xdfs/42#-KpEeJYCoUJtvcD1VHAu:-KpHHnmL47hjI-Sz8PNc:b-896fix) ([raw file](https://github.com/powershell/xdfs/blob/ae1280e0900c100d9ce7e0d658d58d3b18b439df/README.md#L3)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Suggest adding to headers instead (see comment in PR over at xStorage) so that MD013 can be enabled.
Example over at xSQLServer and xFailOverCluster.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/42#-:-KpHHrGB4xiBPmaATY-u:b4ar5cm)*

**Comment by johlju** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/42)*

**Comment by johlju** [comment]
:lgtm:

I know what you mean! On holiday as well, also trying to catch up (and having fun) :smile: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/42#-:-KpKLTiUonuTVnA-P9Yb:b6ar4sq)*

**Pull request merged**
