### PR TITLE
xDFSReplicationGroupMembership: add support for staging quota size - Fixes #77

### LINKED ISSUE #77: xDFSReplicationMembership - add support for modifying staging quota
#### Details of the scenario you tried and the problem that is occurring
When creating or modifying a DFS replication group membership, the staging quota size is left at the default of 4gb
#### Suggested solution to the issue
Add parameter to the xDFSReplicationGroup to allow setting the staging quota size
#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
        DFSReplicationGroupMembership RGWebSiteMembershipHub
        {
            GroupName = 'WebSite'
            FolderName = 'WebSiteFiles'
            ComputerName = $HubComputerName
            ContentPath = 'd:\inetpub\wwwroot\WebSiteFiles'
            StagingPathQuotaInMB = 81960 # Proposed new parameter
            PrimaryMember = $true
            PSDSCRunAsCredential = $Credential
            DependsOn = '[DFSReplicationGroupFolder]RGWebSiteFolder'
        } # End of RGWebSiteMembershipHub Resource

```

#### The operating system the target node is running
OsName               : Microsoft Windows 10 Enterprise
OsOperatingSystemSKU : EnterpriseEdition
OsArchitecture       : 64-bit
WindowsVersion       : 1709
WindowsBuildLabEx    : 16299.431.amd64fre.rs3_release_svc_escrow.180502-1908
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.16299.611
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.611
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
'dev'

### PR DESCRIPTION
**Pull request by murrahjm**
#### Pull Request (PR) description
Add support for modifying staging quota size in MSFT_DFSReplicationGroupMembership

#### This Pull Request (PR) fixes the following issues
- Fixes #77 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/78)

### CODE REVIEW

**Comment by johlju** [comment]
@murrahjm Thanks for adding this! I requested a review from @PlagueHO. He is a bit busy with his day job, but he will come around a review this as soon as he has a chance.

**Comment by PlagueHO** [comment]
Cool! Thanks @murrahjm - I'll get onto this tomorrow night. Thank you @johlju :grin:

**Comment by PlagueHO** [comment]
I completely dropped the ball on this one. Sorry @murrahjm - I'm reviewing now.

**Review by PlagueHO — APPROVED** [review]
Wow! This is +++ fantastic - absolutely top job.

:lgtm:

> Reviewed 6 of 9 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/78#-:-LQMFeZl7pzxozL6D6_h:b7tr6kq)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
