### PR TITLE
Updated pipeline to publish code coverage - Fixes #116

### LINKED ISSUE #115: Update Sampler Build Tasks
Update the Sampler Build tasks as per this blog post: https://dsccommunity.org/blog/updating-sampler-github-tasks/

### LINKED ISSUE #116: Enable Code Coverage Reporting
Enable code coverage reporting as per this blog post: https://dsccommunity.org/blog/add-codecov-support-to-repository/

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description

This PR updates the pipeline to add code coverage reporting and also to use GitHub sampler taksks.

#### This Pull Request (PR) fixes the following issues

- Fixes #115 
- Fixes #116 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in the resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

@johlju - would you mind reviewing when you have time?

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/117)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/117)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[azure-pipelines.yml, line 130 at r1](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYU3IsV4WQOHiWn6Zur:-MYU3IsV4WQOHiWn6Zus:b-4x9ay3) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/5a7ef2cf7b31c30e9e777739cba519531a7713ef/azure-pipelines.yml#L130)):*
> ```
> PublishBuildArtifacts@1
> ```

Should be *PipelineArtifact, or change the task i code cove job. Now it fails to download the test artifact. 
___
*[azure-pipelines.yml, line 172 at r1](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYU3uDe2uFsjN1pDPGO:-MYU3uDf63B5DKFZTWJm:bz8pqw2) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/5a7ef2cf7b31c30e9e777739cba519531a7713ef/azure-pipelines.yml#L172)):*
> ```YAML
>               summaryFileLocation: '$(Build.SourcesDirectory)/$(buildFolderName)/$(testResultFolderName)/JaCoCo_coverage.xml'
>               pathToSources: '$(Build.SourcesDirectory)/$(sourceFolderName)/'
> ```

Also missing the task to upload to Codecov.io. Is that intentional then there are a few changes in this PR that can be reverted. :)

**Comment by PlagueHO** [comment]
@johlju - ah I see! I was looking at the old blog post. All my pipelines need to be updated to use the new tasks. So hold off on reviewing the other PR's for now as I'll need to fix them all.

**Review by PlagueHO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/117)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[azure-pipelines.yml, line 130 at r1](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYU3IsV4WQOHiWn6Zur:-MYXHqhL5XQbDuiG9RoG:b-896fix) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/5a7ef2cf7b31c30e9e777739cba519531a7713ef/azure-pipelines.yml#L130)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> PublishBuildArtifacts@1
> ```

Should be *PipelineArtifact, or change the task i code cove job. Now it fails to download the test artifact. 
</blockquote></details>

Done.
___
*[azure-pipelines.yml, line 172 at r1](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYU3uDe2uFsjN1pDPGO:-MYXHt1iCZdUcosi1WKz:b-896fix) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/5a7ef2cf7b31c30e9e777739cba519531a7713ef/azure-pipelines.yml#L172)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Also missing the task to upload to Codecov.io. Is that intentional then there are a few changes in this PR that can be reverted. :)
</blockquote></details>

Done.

**Review by PlagueHO — COMMENTED** [review]
Should be good to go, @johlju . I'll fix up the others today.

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-:-MYXHunuEjgFuTrZdn6U:buplj3m)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @johlju)

**Review by johlju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/117)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

*[a discussion](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYZ02NSBDGfUYDNZrtG:-MYZ02NT85B0Ud5ioY_A:by0lja9) (no related file):*
See comments in https://github.com/dsccommunity/xPSDesiredStateConfiguration/pull/714#pullrequestreview-638303903

To fix error messages:

https://dev.azure.com/dsccommunity/DFSDsc/_build/results?buildId=4395&view=results

Have not seen it fail to find NUnit*.xml so hopefully that will be fixed with the comments on that link.

---

**Review by PlagueHO — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/117)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @johlju)

*[a discussion](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYZ02NSBDGfUYDNZrtG:-MYd37srAmoaCrADQk9J:b-896fix) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

See comments in https://github.com/dsccommunity/xPSDesiredStateConfiguration/pull/714#pullrequestreview-638303903

To fix error messages:

https://dev.azure.com/dsccommunity/DFSDsc/_build/results?buildId=4395&view=results

Have not seen it fail to find NUnit*.xml so hopefully that will be fixed with the comments on that link.
</blockquote></details>

Done.

---

**Review by johlju — CHANGES_REQUESTED** [review]
I have to update the blog post if this change works. Need to remove the `dscBuildVariable` too. 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-:-MYegwuc-skT85PqyKr7:b-2giwoy)* status: all files reviewed, 8 unresolved discussions (waiting on @PlagueHO)

___
*[azure-pipelines.yml, line 82 at r3](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYeg9kL5rSJD4uZ5CMT:-MYeg9kL5rSJD4uZ5CMU:b-pf3m3y) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/e296a225dd5edfc5304578edff3cf4892f02a058/azure-pipelines.yml#L82)):*
> ```
> $(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
> ```

Still errors on missing NUnit*.xml file. Let us try change to this (absolute path):
```
'$(Build.SourcesDirectory)/$(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
```
___
*[azure-pipelines.yml, line 93 at r3](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYeeU7o1pjMNUCQFf6J:-MYeeU7o1pjMNUCQFf6K:b-2t034z) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/e296a225dd5edfc5304578edff3cf4892f02a058/azure-pipelines.yml#L93)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>           - powershell: |
>               $repositoryOwner,$repositoryName = $env:BUILD_REPOSITORY_NAME -split '/'
>               echo "##vso[task.setvariable variable=RepositoryOwner;isOutput=true]$repositoryOwner"
>               echo "##vso[task.setvariable variable=RepositoryName;isOutput=true]$repositoryName"
>             name: dscBuildVariable
>             displayName: 'Set Environment Variables'
> ```
</details>


Not necessary any longer.
___
*[azure-pipelines.yml, line 126 at r3](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYefsOfExJ78oyfnehY:-MYefsOfExJ78oyfnehZ:b-wgfl3v) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/e296a225dd5edfc5304578edff3cf4892f02a058/azure-pipelines.yml#L126)):*
> ```
> $(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
> ```

Still errors on missing NUnit*.xml file. Let us try change to this (absolute path):
```
'$(Build.SourcesDirectory)/$(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
```

The file is uploaded as part of the artifact in the next task so it do exist.
___
*[azure-pipelines.yml, line 145 at r3](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYefW2V5wVK-oIHj6jD:-MYefW2V5wVK-oIHj6jE:b-97wwvf) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/e296a225dd5edfc5304578edff3cf4892f02a058/azure-pipelines.yml#L145)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>           - pwsh: |
>               $repositoryOwner,$repositoryName = $env:BUILD_REPOSITORY_NAME -split '/'
>               echo "##vso[task.setvariable variable=RepositoryOwner;isOutput=true]$repositoryOwner"
>               echo "##vso[task.setvariable variable=RepositoryName;isOutput=true]$repositoryName"
>             name: dscBuildVariable
>             displayName: 'Set Environment Variables'
> ```
</details>


We can remove this. The variable `dscBuildVariable` is no longer used.
___
*[azure-pipelines.yml, line 217 at r3](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYeg_LS698J8dHmH0s9:-MYeg_LS698J8dHmH0sA:b-pf3m3y) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/e296a225dd5edfc5304578edff3cf4892f02a058/azure-pipelines.yml#L217)):*
> ```
> $(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
> ```

Still errors on missing NUnit*.xml file. Let us try change to this (absolute path):
```
'$(Build.SourcesDirectory)/$(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
```
___
*[azure-pipelines.yml, line 229 at r3](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYeeMWPEbCaoIJR94ic:-MYeeMWPEbCaoIJR94id:b-2t034z) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/e296a225dd5edfc5304578edff3cf4892f02a058/azure-pipelines.yml#L229)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>           - powershell: |
>               $repositoryOwner,$repositoryName = $env:BUILD_REPOSITORY_NAME -split '/'
>               echo "##vso[task.setvariable variable=RepositoryOwner;isOutput=true]$repositoryOwner"
>               echo "##vso[task.setvariable variable=RepositoryName;isOutput=true]$repositoryName"
>             name: dscBuildVariable
>             displayName: 'Set Environment Variables'
> ```
</details>


Not necessary any longer.
___
*[azure-pipelines.yml, line 261 at r3](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYegcgZAtgD3AfXeKtu:-MYegcgZAtgD3AfXeKtv:b-pf3m3y) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/e296a225dd5edfc5304578edff3cf4892f02a058/azure-pipelines.yml#L261)):*
> ```
> $(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
> ```

Still errors on missing NUnit*.xml file. Let us try change to this (absolute path):
```
'$(Build.SourcesDirectory)/$(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
```
___
*[azure-pipelines.yml, line 306 at r3](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYegewl9pWuuAjT4mQ9:-MYegewl9pWuuAjT4mQA:b-pf3m3y) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/e296a225dd5edfc5304578edff3cf4892f02a058/azure-pipelines.yml#L306)):*
> ```
> $(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
> ```

Still errors on missing NUnit*.xml file. Let us try change to this (absolute path):
```
'$(Build.SourcesDirectory)/$(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
```

**Review by PlagueHO — COMMENTED** [review]
@johlju - found the problem after I reviewed/merged your blog changes - don't think the absolute path is required. I was just missing quotes (copy/paste fail).

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-:-MYhtad_21MzS8xp-Obm:bqk0bqh)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @johlju)

___
*[azure-pipelines.yml, line 82 at r3](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYeg9kL5rSJD4uZ5CMT:-MYhstGA-r1bAvz3wyLr:b-ual1o2) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/e296a225dd5edfc5304578edff3cf4892f02a058/azure-pipelines.yml#L82)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
> ```

Still errors on missing NUnit*.xml file. Let us try change to this (absolute path):
```
'$(Build.SourcesDirectory)/$(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
```
</blockquote></details>

@johlju - just realized what the problem was: Missing ' at the beginning :( So didn't need the absolute path.
___
*[azure-pipelines.yml, line 93 at r3](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYeeU7o1pjMNUCQFf6J:-MYht95tCkZTZs0FA7r7:b-896fix) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/e296a225dd5edfc5304578edff3cf4892f02a058/azure-pipelines.yml#L93)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>           - powershell: |
>               $repositoryOwner,$repositoryName = $env:BUILD_REPOSITORY_NAME -split '/'
>               echo "##vso[task.setvariable variable=RepositoryOwner;isOutput=true]$repositoryOwner"
>               echo "##vso[task.setvariable variable=RepositoryName;isOutput=true]$repositoryName"
>             name: dscBuildVariable
>             displayName: 'Set Environment Variables'
> ```

Not necessary any longer.
</blockquote></details>

Done.
___
*[azure-pipelines.yml, line 126 at r3](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYefsOfExJ78oyfnehY:-MYhtLs1E8lrHd-bJ7Jr:bek9gw) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/e296a225dd5edfc5304578edff3cf4892f02a058/azure-pipelines.yml#L126)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
> ```

Still errors on missing NUnit*.xml file. Let us try change to this (absolute path):
```
'$(Build.SourcesDirectory)/$(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
```

The file is uploaded as part of the artifact in the next task so it do exist.
</blockquote></details>

As above.
___
*[azure-pipelines.yml, line 145 at r3](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYefW2V5wVK-oIHj6jD:-MYhtJvn-3BYzIXjMl4c:b-896fix) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/e296a225dd5edfc5304578edff3cf4892f02a058/azure-pipelines.yml#L145)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>           - pwsh: |
>               $repositoryOwner,$repositoryName = $env:BUILD_REPOSITORY_NAME -split '/'
>               echo "##vso[task.setvariable variable=RepositoryOwner;isOutput=true]$repositoryOwner"
>               echo "##vso[task.setvariable variable=RepositoryName;isOutput=true]$repositoryName"
>             name: dscBuildVariable
>             displayName: 'Set Environment Variables'
> ```

We can remove this. The variable `dscBuildVariable` is no longer used.
</blockquote></details>

Done.
___
*[azure-pipelines.yml, line 217 at r3](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYeg_LS698J8dHmH0s9:-MYhtNXq29ZX-njCc9_d:bribihm) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/e296a225dd5edfc5304578edff3cf4892f02a058/azure-pipelines.yml#L217)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
> ```

Still errors on missing NUnit*.xml file. Let us try change to this (absolute path):
```
'$(Build.SourcesDirectory)/$(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
```
</blockquote></details>

As above.
___
*[azure-pipelines.yml, line 229 at r3](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYeeMWPEbCaoIJR94ic:-MYhtG3a7zZiFbEm2RcE:b-896fix) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/e296a225dd5edfc5304578edff3cf4892f02a058/azure-pipelines.yml#L229)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
>           - powershell: |
>               $repositoryOwner,$repositoryName = $env:BUILD_REPOSITORY_NAME -split '/'
>               echo "##vso[task.setvariable variable=RepositoryOwner;isOutput=true]$repositoryOwner"
>               echo "##vso[task.setvariable variable=RepositoryName;isOutput=true]$repositoryName"
>             name: dscBuildVariable
>             displayName: 'Set Environment Variables'
> ```

Not necessary any longer.
</blockquote></details>

Done.
___
*[azure-pipelines.yml, line 261 at r3](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYegcgZAtgD3AfXeKtu:-MYhtOlrBgmNRAGl3GBw:bribihm) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/e296a225dd5edfc5304578edff3cf4892f02a058/azure-pipelines.yml#L261)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
> ```

Still errors on missing NUnit*.xml file. Let us try change to this (absolute path):
```
'$(Build.SourcesDirectory)/$(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
```
</blockquote></details>

As above.
___
*[azure-pipelines.yml, line 306 at r3](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-MYegewl9pWuuAjT4mQ9:-MYhtPj4Ce3v3tWf_mLc:bribihm) ([raw file](https://github.com/dsccommunity/dfsdsc/blob/e296a225dd5edfc5304578edff3cf4892f02a058/azure-pipelines.yml#L306)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> $(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
> ```

Still errors on missing NUnit*.xml file. Let us try change to this (absolute path):
```
'$(Build.SourcesDirectory)/$(buildFolderName)/$(testResultFolderName)/NUnit*.xml'
```
</blockquote></details>

As above.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/117#-:-MYhx2vmCncln202ZyvM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @PlagueHO)

**Pull request merged**
