### PR TITLE
Add xDFSNamespaceServerConfiguration resource - Fixes #16

### LINKED ISSUE #16: [New Resource] xDFSNamespaceServerConfiguration
Should be a IsSingleUse resource. Will use `Get-DfsnServerConfiguration` and `Set-DfsnServerConfiguration`.

Allows control of the following parameters:
LdapTimeoutSec            : 30
PreferLogonDC             :
EnableSiteCostedReferrals :
EnableInsiteReferrals     :
SyncIntervalSec           : 3600
UseFqdn                   : False

### PR DESCRIPTION
**Pull request by PlagueHO**
This has been primarily added to enable FQDN mode to be turned on for DFS Namespace servers. Two other DFS Namespace server parameters were also exposed.
LdapTimeoutSec
SyncIntervalSec

Because I am using files.trimTrailingWhitespace in VS Code, some trailing white space was also trimmed from the Readme.md.

This relates to issue #15, but I will still need to determine if the other DFSN resources require changes to support FQDN mode, so I'm leaving #15 open until I've checked this.

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/xdfs/17)

### CODE REVIEW

**Comment by PlagueHO** [comment]
@TravisEz13  - if you get a spare moment, would you be able to review this PR for me? No rush - not a critical feature or fix.

Thanks!

**Comment by TravisEz13** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[DSCResources/MSFT_xDFSNamespaceServerConfiguration/MSFT_xDFSNamespaceServerConfiguration.schema.mof, line 5 [r1]](https://reviewable.io:443/reviews/powershell/xdfs/17#-KKe-DVXdDSVp1fJ-lCF:-KKe-DVXdDSVp1fJ-lCG:-2013837932) ([raw file](https://github.com/powershell/xdfs/blob/8a3c3f5a76a1cba9ccba97ddf523a982e840121a/DSCResources/MSFT_xDFSNamespaceServerConfiguration/MSFT_xDFSNamespaceServerConfiguration.schema.mof#L5)):_

> ```
> {
>     [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'"), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
>     [Write, Description("Specifies a time-out value, in seconds, for Lightweight Directory Access Protocol (LDAP) requests for the DFS namespace server.")] Uint32 LdapTimeoutSec;
> ```

should we spell out seconds?

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/17)_

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[DSCResources/MSFT_xDFSNamespaceServerConfiguration/MSFT_xDFSNamespaceServerConfiguration.schema.mof, line 5 [r1]](https://reviewable.io:443/reviews/powershell/xdfs/17#-KKe-DVXdDSVp1fJ-lCF:-KKgkS78gNqNQsW0bq-P:1989432577) ([raw file](https://github.com/powershell/xdfs/blob/8a3c3f5a76a1cba9ccba97ddf523a982e840121a/DSCResources/MSFT_xDFSNamespaceServerConfiguration/MSFT_xDFSNamespaceServerConfiguration.schema.mof#L5)):_
<details><summary>

<i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>



> should we spell out seconds?
> </details>
> @TravisEz13, I defined it as Sec to match the underlying cmdlet property, but if it you think it would be clearer as Seconds, I can change it - I'd take your advice on this one.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/17)_

**Comment by TravisEz13** [comment]
@HemantMahawar What do you think?

**Comment by TravisEz13** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[DSCResources/MSFT_xDFSNamespaceServerConfiguration/MSFT_xDFSNamespaceServerConfiguration.schema.mof, line 5 [r1]](https://reviewable.io:443/reviews/powershell/xdfs/17#-KKe-DVXdDSVp1fJ-lCF:-KKlLAobUa2HEBs4rPpk:1893550194) ([raw file](https://github.com/powershell/xdfs/blob/8a3c3f5a76a1cba9ccba97ddf523a982e840121a/DSCResources/MSFT_xDFSNamespaceServerConfiguration/MSFT_xDFSNamespaceServerConfiguration.schema.mof#L5)):_
<details><summary>

<i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>



> @TravisEz13, I defined it as Sec to match the underlying cmdlet property, but if it you think it would be clearer as Seconds, I can change it - I'd take your advice on this one.
> </details>
> @hemant

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/17)_

**Comment by HemantMahawar** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[DSCResources/MSFT_xDFSNamespaceServerConfiguration/MSFT_xDFSNamespaceServerConfiguration.schema.mof, line 5 [r1]](https://reviewable.io:443/reviews/powershell/xdfs/17#-KKe-DVXdDSVp1fJ-lCF:-KKoOHeka2lROKFJA1ze:-1270883123) ([raw file](https://github.com/powershell/xdfs/blob/8a3c3f5a76a1cba9ccba97ddf523a982e840121a/DSCResources/MSFT_xDFSNamespaceServerConfiguration/MSFT_xDFSNamespaceServerConfiguration.schema.mof#L5)):_
<details><summary>

<i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>



> @hemant
> </details>
> Sec is fine. We use "Sec" in PowerShell instead of seconds as a suffix to time related properties. Also built-in WaitFor\* resources follow the same pattern on its time related property (RetryIntervalSec)

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/17)_

**Comment by PlagueHO** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

_[DSCResources/MSFT_xDFSNamespaceServerConfiguration/MSFT_xDFSNamespaceServerConfiguration.schema.mof, line 5 [r1]](https://reviewable.io:443/reviews/powershell/xdfs/17#-KKe-DVXdDSVp1fJ-lCF:-KL3bd_RMqx0NdkutpoI:-257421372) ([raw file](https://github.com/powershell/xdfs/blob/8a3c3f5a76a1cba9ccba97ddf523a982e840121a/DSCResources/MSFT_xDFSNamespaceServerConfiguration/MSFT_xDFSNamespaceServerConfiguration.schema.mof#L5)):_
<details><summary>

<i>Previously, HemantMahawar (Hemant Mahawar) wrote…</i></summary>



> Sec is fine. We use "Sec" in PowerShell instead of seconds as a suffix to time related properties. Also built-in WaitFor\* resources follow the same pattern on its time related property (RetryIntervalSec)
> </details>
> Thanks @hemant - @TravisEz13 - it should hopefully be ready for your final review! Thanks!

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xdfs/17)_

**Pull request merged**
