### PR TITLE
DFSDsc: Remove pipeline file `build.psd1`

### LINKED ISSUE #130: Azure Pipelines status showing as 'failed'; latest build returns 'Pipeline not found'
This really is a nit pick - blame @johlju for encouraging me to report things in #129 :)

For some reason on the front page the 'Azure Pipelines' build status shows as 'FAILED':

image

Clicking this returns the results for a (failed) 4.5.0-preview.2 build.

image

From there clicking 'Pipelines' shows the successful 5.0.0 build:

image

But clicking that link for more details shows 'Pipeline not found':

image

Not a big deal but seems the automated build process is still a bit 'off'

### PR DESCRIPTION
**Pull request by johlju**
#### This Pull Request (PR) fixes the following issues

Fixes #130. Once we publish 5.0.1.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the
      file CHANGELOG.md. Entry should say what was changed and how that
      affects users (if applicable), and reference the issue being resolved
      (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/DFSDsc/131)

### CODE REVIEW

**Review by Borgquite — APPROVED** [review]
Not sure if my permissions are enough but as requested!

**Comment by johlju** [comment]
@Borgquite apparently just contributor reviewer can't make the status check to be green when approving - looked at the settings and there are not a way to enable that either. :/ Regardless, your approvalmake it possible for me to override the status check. Thank you!

**Comment by johlju** [comment]
- DFSDsc
  - Removed the pipeline files `build.psd1` as it is no longer needed.

**Comment by johlju** [comment]
Accidently closed the PR, merging now.

**Pull request merged**
