### PR TITLE
BREAKING CHANGE: MSFT_DFSNamespaceRoot/MSFT_DFSNamespaceFolder: DFSNamespace Support for ReferralStatus (State) Modification

### PR DESCRIPTION
**Pull request by thesmall**
#### Pull Request (PR) description
BREAKING CHANGE:
 - Add support for setting a DFS Namespace root target's referral status (state) to be either Online or Offline
   in MSFT_DFSNamespaceRoot. State is now a required parameter.
 - Add support for setting a DFS Namespace folder target's referral status (state) to be either Online or Offline
   in MSFT_DFSNamespaceFolder. State is now a required parameter.
 - Update examples to support new required parameter.

#### This Pull Request (PR) fixes the following issues
This pull request does not fix any issues. 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md in the resource folder.
- [x] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/dfsdsc/97)

### CODE REVIEW

**Comment by mfagotto** [comment]
Hi, 
is there any plan make this feature available  in future releases?

**Comment by gaelcolas** [comment]
Hi, I did not spot this PR before, but it looks like it'd need some tests setup unless I'm not reading the codcov report rights.
I know @PlagueHO is busy these days so he won't be able to make this PR work soon if it does not pass the tests.

I'm happy to review and merge if and when the test passes if Dan is busy, or to assist if someone need help.

@heimdallreport feel free to fork his branch and continue the work in a new PR, or ask @thesmall if you can help getting this PR to pass the tests.

**Comment by thesmall** [comment]
Hey all. @gaelcolas you're correct in the assessment that there are no tests present. Truth of the matter is that, while I can write the code to actually make the DSC Resource work, I have almost no idea how to write the appropriate and necessary tests. 

If someone would be willing to work with me on getting the tests written, I would be grateful and would be happy to further facilitate getting this branch merged.

**Comment by PlagueHO** [comment]
Hi @heimdallreport - not sure how I missed this. And apologies to @thesmall. I suspect it was during the transition to the new CI pipelines.

I'd love to get this through, so if you're still working on this @thesmall, keen to get the conflicts resolved.

**Comment by Borgquite** [comment]
@PlagueHO FYI This merge can be discarded since it was included in #126

**Comment by PlagueHO** [comment]
Thanks @Borgquite - closing as addressed in #126.

**Pull request closed without merging**
