### PR TITLE
Updated PR Template

### PR DESCRIPTION
**Pull request by PlagueHO**
#### Pull Request (PR) description
Updated PR Template.

#### This Pull Request (PR) fixes the following issues
None.

#### Task list
- [ ] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/73)

### CODE REVIEW

**Review by johlju — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/73)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by johlju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/73)* status: all files reviewed, 1 unresolved discussion (waiting on @PlagueHO)

___
*[.github/PULL_REQUEST_TEMPLATE.md, line 39 at r1](https://reviewable.io/reviews/powershell/dfsdsc/73#-LKc4JF7CAqVxuyh2h8y:-LKc4JF8Cu-RU1-74Pop:b22ka9d) ([raw file](https://github.com/powershell/dfsdsc/blob/1b3ab13b3dc3a0f79980cc38b2cdd500e7b7e68d/.github/PULL_REQUEST_TEMPLATE.md#L39)):*
> ```
> in resource folder
> ```

Maybe 'in the resource folder'?

**Review by PlagueHO — COMMENTED** [review]
All done @johlju

> *[Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/73#-:-LKehEdE1yTEH5DbJizY:b-gwkao6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @johlju)

___
*[.github/PULL_REQUEST_TEMPLATE.md, line 39 at r1](https://reviewable.io/reviews/powershell/dfsdsc/73#-LKc4JF7CAqVxuyh2h8y:-LKehDkF5XDtR5nQK5Qw:b-896fix) ([raw file](https://github.com/powershell/dfsdsc/blob/1b3ab13b3dc3a0f79980cc38b2cdd500e7b7e68d/.github/PULL_REQUEST_TEMPLATE.md#L39)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> in resource folder
> ```

Maybe 'in the resource folder'?
</blockquote></details>

Done.

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/powershell/dfsdsc/73#-:-LKfAoBtDxRdTvY0-dh1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
